; 2023-02-10
; Copyright 2023 Tiemo Benedikt Schroeder
; (see License.txt)

; Standard Vocabulary for Iconic
; ==============================
;
; Implementation of a standard vocabulary for Iconic - the Universal
; Icon Language (www.iconlang.net). Write words by entering their nickname
; and then pressing space or enter. Close the script via escape. Reload it
; via Ctrl+Alt+R. Activate or deactivate it with Ctrl+Alt+A.
; The symbol for activation is 'H' like 'Hotkey', for disactivation
; 'S' like 'Stop'.

; 1 Script Management
; ===================

; Exit the script with Escape
Esc::exitapp
; Press Ctrl+Alt+R to reload the script
^!r::Reload
; Press Ctrl+Alt+A to toggle the script on and off
^!a::Suspend

; 2 Vocabulary
; ============

:o:for::🎁
:o:against::✊️
:o:ag::✊️
:o:anti::✊️
:o:do::🎬
:o:action::🎬
:o:act::🎬
:o:be::📦
:o:have::👜
:o:tohave::👜🎬
:o:has::👜
:o:similar::🤲
:o:sim::🤲
:o:like::🤲
:o:tolike::❤️🎬
:o:than::⚖️
:o:tha::⚖️
:o:instead::🔀
:o:inst::🔀
:o:by::🔨
:o:via::🔨
:o:b::🔨
:o:made::🧱
:o:md::🧱
:o:part::💦
:o:pr::💦
:o:place::⚓
:o:pl::⚓
:o:time::🕒
:o:t::🕒
:o:degree::📏
:o:deg::📏
:o:from::⛲
:o:fr::⛲
:o:to::📬
:o:become::✨
:o:bec::✨
:o:subject::2?
:o:subject1::☝️💬💦
:o:subject2::💭⭐
:o:sub::☝️
:o:s::☝️
:o:object::2?
:o:object1::🔍💬💦
:o:object2::❗
:o:toobject::🙅🎬
:o:ob::🔍
:o:o::🔍
:o:because::💡
:o:cause::2?
:o:tocause::🔥⭐🎬
:o:cause::💡⭐
:o:coz::💡
:o:sothat::🔥
:o:so::🔥
:o:tocoerce::🔥🎬
:o:let::🔥
:o:but::⚡️
:o:though::⚡️
:o:although::⚡️
:o:despite::⚡️
:o:inspite::⚡️
:o:topic::💭
:o:tp::💭
:o:about::2?
:o:about1::💭
:o:about2::⚪
:o:regarding::💭
:o:and::➕
:o:with::➕
:o:also::➕
:o:without::➖
:o:nor::➖
:o:neither::➖
:o:dash::➖
:o:or::✖️
:o:either::✖️
:o:andor::➕✖️
:o:per::➗
:o:/::➗
:o:>::➡️
:o:if::➡️⭐
:o:<::⬅️
:o:provided::⬅️⭐
:o:not::⛔
;:o:don''t::⛔
:o:dont::⛔
:o:donot::⛔
:o:only::🌴
:o:onl::🌴
:o:all::♾️
:o:every::♾️
:o:most::3?
:o:most1::♾️⚖️
:o:most2::♾️⚪
:o:most3::♾️⚖️⬆️🤲
:o:more::2?
:o:more1::⚖️
:o:more2::➕🤲
:o:?::❓
:o:questionmark::❓
:o:what::❓
:o:which::❓
:o:!::❗
:o:exclamationmark::❗
:o:some::❗
:o:something::❗
:o:thing::❗
:o:things::❗❗
:o:little::🤏
:o:alittle::🤏
:o:lot::❗❗
:o:alot::❗❗
:o:any::♾️❗
:o:anything::♾️❗
:o:<1::❣️
:o:heartmark::❣
:o:this::👇
:o:ts::👇
:o:the::👇
:o:that::👆
:o:tt::👆
:o:lit::👌
:o:literal::👌
:o:literally::👌
:o:*::⭐
:o:asterisk::⭐
:o:fig::⭐
:o:figurative::⭐
:o:circa::⚪
:o:ca::⚪
:o:about::2?
:o:about1::💭
:o:about2::⚪
:o:example::〰️
:o:ex::〰️
:o:~::〰️
:o:i::👈
:o:I::👈
:o:me::👈
:o:my::👈
:o:we::👈👈
:o:our::👈👈
:o:us::👈👈
:o:you::👉
:o:y::👉
:o:u::👉
:o:your::👉
:o:youall::👉👉
:o:yall::👉👉
:o:heshe::👆🧒
:o:hisher::👆🧒
:o:himher::👆🧒
:o:he::👆👨
:o:she::👆👩
:o:it::👆
:o:his::👆👨
:o:her::👆👩
:o:its::👆
:o:that::👆
:o:thatall::👆👆
:o:they::2?
:o:they1::👆🧒
:o:they2::👆👥
:o:their::2?
:o:their::👆🧒
:o:their::👆👥
:o:this::👇
:o:thisall::👇👇
:o:person::🧒
:o:ps::🧒
:o:someone::❗🧒
:o:group::👥
:o:gr::👥
:o:please::🙏
:o:pls::🙏
:o:plz::🙏
:o:tothank::🙏🙏🎬
:o:thanks::🙏🙏
:o:thankyou::🙏🙏
:o:thx::🙏🙏
:o:sry::🙇
:o:sorry::2?
:o:sorry1::🙇
:o:sorry2::🥺
:o:invite::👋⭐
:o:inv::👋⭐
:o:maybe::🤔
:o:might::🤔
:o:seem::🌟
:o:seems::🌟
:o:tothink::💭🎬
:o:tofeel::2?
:o:tofeel1::❤️⭐🎬
:o:tofeel2::✋️⭐🎬
:o:can::2?
:o:can1::💪
:o:can2::🥫
:o:able::💪
:o:thumbsup::👍👌
:o:may::👍
:o:allowed::👍
:o:thumbsdown::👎
:o:maynot::👎
:o:notallowed::👎
:o:must::⚠️
:o:should::2?
:o:should1::☝️
:o:should2::🤔🤔
:o:will::2?
:o:will1::🚶⭐
:o:will2::💖
:o:goingto::🚶⭐
:o:try::👀⭐
:o:attempt::👀⭐
:o:start::⛲
:o:begin::⛲
:o:continue::👣
:o:con::👣
:o:finish::📬
:o:fin::📬
:o:stop::🛑
:o:love::❤️
:o:loveto::❤️
:o:hate::💢
:o:hateto::💢
:o:sparkleheart::💖
:o:want::💖
:o:wantto::💖
:o:brokenheart::💔
:o:notwant::💔
:o:nwant::💔
:o:let::🔥
:o:coerce::🔥
:o:sothat::🔥
:o:smile::🙂
:o:easy::🙂
:o:enough::🙂
:o:sufficient::👍⚪
:o:exasperate::😧
:o:dif::😧
:o:diff::😧
:o:difficult::😧
:o:notenough::😧
:o:hard::2?
:o:hard1::😧
:o:hard2::🧱🤲
:o:goal::🏁
:o:intend::🏁
:o:intention::🏁⭐
:o:facedown::🙃
:o:upsidedown::🙃
:o:oops::🙃
:o:toomuch::🤯
:o:toom::🤯
:o:too::2?
:o:too1::🤯
:o:too2::➕
:o:noteven::➖
:o:help::🎁
:o:toget::📨🎬
:o:have::👜
:o:!::❗
:o:!!::❗❗
:o:!!!::❗❗❗
:o:exclamationmark::❗
:o:?::❓
:o:??::❓❓
:o:???::❓❓❓
:o:questionmark::❓
:o:.::▪️
:o:fullstop::▪️
:o:,::▫️
:o:comma::▫️
:o:;::◻️
:o:;::semicolon
:o:a::❗
:o:an::❗
:o:about::2?
:o:about1::💭
:o:about2::⚪
;:o:across::👆⚓📬
:o:toact::▶️🎬
:o:actor::2?
:o:actor1::🎬🧒
:o:actor2::🎭🧒
:o:active::❗🎬
:o:activity::🎬
:o:add::➕
:o:afraid::😨
:o:after::➡️
:o:again::↩️🕒
:o:age::4?
:o:age1::⬅️⌛
:o:age2::👴✨🎬
:o:age3::⬅️🕒⌛
:o:age4::🧒⌛
:o:ago::⬅️🕒
:o:toagree::🤝⭐🎬
:o:air::💨
:o:all::♾️
:o:alone::🌴🤲
:o:along::🧵🤲⚓
:o:already::😮👇🕒
:o:always::♾️🕒
:o:am::📦
:o:and::➕
:o:angry::😤🤲
:o:another::🔀
:o:toanswer::↩️🤲💬🎬
:o:any::♾️❗
:o:anyone::♾️❗🧒
:o:anytime::♾️❗🕒
:o:toappear::2?
:o:toappear1::🌟✨🎬
:o:toappear2::🌟🎬
:o:apple::🍎
:o:are::📦
:o:area::⚪⚓
:o:arm::🧍💪
:o:army::⚔️👥
:o:around::⚪⚓
:o:toarrive::🚶📬🎬
:o:art::🎨🎵〰️
;:o:as::📦
:o:toask::2?
:o:toask1::"❓"💬🎬
:o:toask2::🙏🎬
;:o:at::2?
;:o:at1::⚓
;:o:at2::🕒
:o:toattack::⚔️⛲🎬
:o:attack::⚔️⛲🎬
:o:aunt::👪🧍➡👩
:o:autumn::🍂↘️🕒
:o:away::🚶💨🤲
:o:baby::👶
:o:back::2?
:o:back1::🚶➡⚓
:o:back2::↩️🤲
:o:bad::2?
:o:bad1::👎
:o:bad2::👿🤲
:o:bag::👜👌
:o:ball::⚽〰️
:o:bank::💰🏠
:o:base::⛰️💦⬇️
:o:basket::🧺
:o:tobath::🛀🎬
:o:bath::🛀⚓
:o:be::📦
:o:bean::💦👌🍃〰️
:o:bear::🐻
:o:tobear::👶🎬
:o:beautiful::👀👍🤲
:o:pretty::👀👍🤲
:o:handsome::👀👍🤲
:o:bed::🛏
:o:bedroom::🛏⚓
:o:beer::🍺
:o:tobehave::🎬
:o:before::⬅️
:o:begin::⛲
:o:behind::🚶⬅️⚓
:o:bell::🔔
:o:below::⬇️⚓
:o:under::⬇️⚓
:o:beside::🧍⬇️⚓
:o:besides::👇⚖️
:o:best::♾️⚖️👍
:o:better::⚖️👍
:o:between::2❗⏺️⚓
:o:big::🐘🤲
:o:bird::🐦
:o:birth::👶☝️⛲🎬
:o:tobirth::👶☝️⛲🎬
:o:birthday::⛲🎬☀️🕒
:o:bit::2?
:o:bit1::💦
:o:bit2::🤏❗
:o:tobite::🦷🎬
:o:black::🌙🕒🎨
:o:tobleed::❤️💦👌🎬
:o:block::🙅🎬
:o:blood::❤️💦👌
:o:toblow::💨🎬
:o:blue::💧🎨
:o:board::📝🤲❗
:o:boat::🤏🚢
:o:body::🧍
:o:toboil::💨🔥♨️🎬
:o:bone::🦴
:o:book::📖
:o:border::⚪👌💦〰️👌⚓
:o:born::👶🎬
:o:toborrow::🤏🕒📨🎬
:o:both::♾️2
:o:bottle::🧴〰️
:o:bottom::⬇️💦
:o:bowl::🥣
:o:box::📦👌
:o:tobox::🥊🎬
:o:boy::👦
:o:branch::🌳✋️
:o:brave::🦁🤲
:o:bread::🍞〰️
:o:break::3?
:o:tobreak::💥📬🎬
:o:break::🤏🕒🦥
:o:breakfast::☀️↗️🍽️⭐
:o:tobreathe::👄💨🎬
:o:bridge::💧⬆️⚓🚶⚓
:o:bright::☀️🕒🤲
:o:tobring::👜➕🚶🎬
:o:brother::👪🧒➕👦
:o:brown::☕🎨
:o:brush::🖌️
:o:tobuild::🧱🎬
:o:toburn::🔥👌🎬
:o:business::💰⭐
:o:bus::🚌
:o:busy::❗❗🎬
:o:but::⚡️
:o:tobuy::💰🔀📨🎬
:o:by::🔨
:o:cake::🎂
:o:tocall::📣🎬
:o:can::💪
:o:candle::🕯️
:o:cap::🧢
:o:car::🚗
:o:card::🤏📝
:o:tocare::⚠️🔍👀🎬
:o:careful::⚠️🔍👀🤲
:o:careless::⚠️🔍⛔👀🤲
:o:tocarry::👜🚶🎬
:o:case::2?
:o:case1::🧰
:o:case2::💭
:o:cat::🐈
:o:tocatch::2?
:o:tocatch1::🕸️🎬
:o:tocatch2::💨✋️👜🎬
:o:catch::2?
:o:catch1::📏〰️
:o:catch2::🎣🎬❗
:o:central::♾️⚖️⏺️🤲
:o:century::100🌼➡️❄️🕒
:o:certain::💡🎬🤲
:o:chair::🪑
:o:chance::2?
:o:chance1::💪🎬🕒
:o:chance2::☘️⭐
:o:tochange::🔀🎬
:o:change::🔀🎬
:o:tochase::🏃➕✋️🎬
:o:cheap::🤏💰🤲
:o:cheese::🧀
:o:chicken::🐔
:o:child::👪🤏🧒
:o:children::👪🤏🧒🧒
:o:chocolate::🍫
:o:choice::✖️⭐
:o:tochoose::✖️🎬
:o:circle::⚪👌
:o:city::🏘️
:o:class::👥
:o:clever::🧒👌👍🤲
:o:toclean::💧🧽🎬
:o:clean::💧🧽🎬🤲
:o:clear::👍💧👀🤲
:o:climb::⬆️🚶🎬
:o:clock::🕒👌
:o:cloth::👚🧱⭐
:o:clothes::👚⭐
:o:cloud::☁️
:o:cloudy::☁️🤲
:o:close::=⚓⚪🤲
:o:toclose::🔐🎬
:o:coffee::☕
:o:coat::🥼
:o:coin::💰⚪👌
:o:cold::❄️🤲
:o:collect::👜✨🎬
:o:tocolor::🎨🎬
:o:color::2?
:o:color1::🎨💧
:o:color2::🎨⭐
:o:comb::🧒👌📏〰️
:o:comfortable::🙂🤲
:o:common::♾️⚪🤲
:o:tocompare::⚖️🎬
:o:tocome::👇📬🚶🎬
:o:complete::📬🤲
:o:computer::💻〰️
:o:condition::2?
:o:condition1::⬅️🕒⚠️📦
:o:condition2::❓🤲⭐
:o:continue::👣
:o:tocontrol::🤴🏻🎬
:o:tocook::🍳🎬
:o:cook::🍳🎬🧒
:o:cool::2?
:o:cool1::🤏❄️🤲
:o:cool2::😎
:o:copper::Cu
:o:corn::🌽
:o:corner::📦👌⏺️👌
:o:correct::✔️🤲
:o:cost::💰🔢
:o:tocontain::⏺📦🎬
:o:tocount::🔢🎬
:o:country::2?
:o:country1::🌍🏳️
:o:country2::🌳🌾⚓
;:o:course::
:o:tocover::👒🎬
:o:cover::👒⭐
:o:crash::💥
:o:cross::❌👌
:o:tocry::2?
:o:tocry1::😢🎬
:o:tocry2::😱🎬
:o:cup::☕👌〰️
:o:cupboard::🍽️👌⚓
:o:tocut::🔪🎬
:o:dancer::💃
:o:dance::💃🔨⭐
:o:todance::💃🎬
:o:dangerous::⚠️⭐🤲
:o:dark::🌙🕒🤲
:o:daughter::👪👧
:o:day::☀️🕒
:o:dead::3?
:o:dead1::☠️🤲
:o:dead2::☠️🧒
:o:dead3::☠️👥
:o:todecide::✖️🎬
:o:todecrease::📉🎬
:o:deep::🕳🤲
:o:deer::🦌
:o:todepend::🔗🎬🤲
:o:desk::🪑➕❗
:o:todestroy::💥🎬
:o:todevelop::🧱🎬
:o:todie::☠️🎬
:o:die::🎲
:o:different::🔀
:o:difficult::😧
:o:dinner::☀️↘️🍽️⭐
:o:direction::❓📬🚶🎬
:o:dirty::💩🤲
:o:discover::1.🕒💡✨🎬
:o:dish::2?
:o:dish1::🍽️
:o:dish2::❓🤲🍽️⭐
:o:todo::▶️🎬
:o:dog::🐶
:o:door::🚪
:o:todouble::2❌🔢🎬
:o:double::2❌🔢
:o:down::⬇️
:o:todraw::2?
:o:todraw1::🖌️🎬
:o:todraw2::⬆️✋️🎬
:o:draw3::⚔️➡=
:o:dream::💤👀
:o:dress::2?
:o:dress1::👗
:o:dress2::👚〰️
:o:drink::2?
:o:todrink::🍹🎬
:o:drink::🍹⭐
:o:todrive::🚗🎬
:o:todrop::↘️🔥🎬
:o:drop::💧👌
:o:dry::⛔💧🤲
:o:duck::🦆
:o:toduck::🧒👌🔍↘️🎬
:o:dust::💨👌
:o:duty::⚠️🎬
:o:each::♾️
:o:ear::👂
:o:early::⬅️🕒🤲
:o:toearn::2?
:o:toearn1::💰📨🎬
:o:toearn2::👍📨🎬
:o:earth::2?
:o:earth1::🌍🧱⭐
:o:earth2::🌍👌
:o:east::🧭➡️
:o:easy::🙂🎬🤲
:o:toeat::🍽️🎬
:o:education::🏫⭐
:o:effect::🔥⭐
:o:egg::🥚
:o:eight::8
:o:either::✖️
:o:electric::⚡️⭐
:o:elephant::🐘
:o:else::2?
:o:else1::⛔👇➡️⭐
:o:else2::🔀
:o:empty::🐚🤲
:o:toend::📬🎬
:o:end::📬⭐
:o:enemy::👎👥🧒
:o:toenjoy::😃🎬
:o:enough::🙂
:o:toenter::⏺️📬🚶🎬
:o:equal::=🤲
:o:entrance::🚪⭐
:o:toescape::⏺⚡️📬🏃🎬
:o:even::3?
:o:even1::=🤲
:o:even2::➗2💪🎬🤲
:o:even3::➕
:o:evening::☀️↘️🕒
:o:event::🎬
:o:ever::2?
:o:ever1::♾️🕒💦
:o:ever2::♾️🕒⚖️
:o:every::♾️
:o:everyone::♾️🧒
:o:exact::📏⭐🤲
:o:everybody::♾️🧒
;:o:examination::🔍➕👀🎬
:o:except::⚡️
:o:excited::🚶⭐💭😃🤲
:o:toexercise::2?
:o:toexercise1::🧍👍🔥🎬
:o:toexercise2::🔨🎬
:o:toexpect::🤔🤔🎬
:o:expensive::🐘💰🤲
:o:toexplain::💡🔥🎬
:o:extremely::🔥🔥🤲
:o:eye::👁️
:o:face::🙂👌
:o:fact::✔️⭐❗
:o:tofail::🙃🎬
:o:tofall::↘️🎬
:o:fall::🍂↘️🕒
:o:false::✔️⚡️🤲
:o:family::👪
:o:famous::❗❗🧒☝️💡🎬
:o:far::🗼👀🤲
:o:farm::🍽️⭐🎁🌾🏠
:o:father::👪👨
:o:fast::🏃💨🤲
:o:fat::2?
:o:fat1::🥩💦👰🏻🎨
:o:fat2::🐋🤲
:o:fault::👎💦
:o:fear::😱
:o:tofear::😱🎬
:o:tofeed::🍽️🔥🎬
:o:tofeel::2?
:o:tofeel1::❤️⭐🎬
:o:tofeel2::✋️➕💭🎬
:o:female::♀️
:o:fever::🤒🌡️
:o:few::🌴🌴
:o:tofight::⚔️🎬
:o:fight::⚔️🎬
:o:tofill::⏺️📬⬇️✋️🎬
:o:tofind::👀✨🎬
:o:fine::3?
:o:fine1::🤏🤲
:o:fine2::👍⚪
:o:fine3::💰🥈⚡️
:o:finger::☝️👌
:o:tofinish::📬🎬
:o:fire::🔥
:o:first::2?
:o:first1::1.
:o:first2::♾️⚖️⬅️
:o:fish::🐟
:o:tofish::🎣🎬
:o:fit::🧍👍
:o:five::5
:o:tofix::2?
:o:tofix1::🔧🎬
:o:tofix2::⛔👋🔥🎬
:o:flag::🏳️
:o:flat::📝🤲
:o:tofloat::🌊⬆️⚓🚶🎬
:o:floor::👣⬇️⚓
:o:flour::🌾⛲🧂⭐
:o:flower::🌼
:o:tofly::🐦🎬
:o:fly::🦟🤲❗
:o:tofold::📝📐🎬
:o:fold::📝📐⭐
:o:food::🍽️⭐
:o:fool::🧒👌👎🧒
:o:foot::🦶
:o:football::2?
:o:football1::⚽
:o:football2::🏈
:o:for::🎁
:o:force::🧍💪⭐
:o:foreign::🌍⛔👇🏳️🤲
:o:forest::🌳🌳
:o:toforget::⛔💡✨🎬
:o:toforgive::⛔⚠️🔥🎬
:o:fork::🍴💦⬅️
:o:form::👤⭐
:o:fox::🦊
:o:four::4
:o:tofree::⛓️⚡️🎬
:o:free::⛓️⚡️🤲
:o:freedom::⛓️⚡️
:o:tofreeze::🧊🎬
:o:fresh::🐟💧🤲
:o:friend::👍👥🧒
:o:friendly::👍👥🤲
:o:from::⛲
:o:front::➡🚶⚓
:o:fruit::🍎〰️
:o:full::3?
:o:full1::❗❗⏺️
:o:full2::📬🤲
:o:full3::♾️🤲
:o:fun::😃
:o:funny::😂🤲
:o:furniture::🪑〰️
:o:further::🔀⚓➕📬
:o:future::➡️🕒
:o:togame::🎮🎬
:o:game::🎮⭐
:o:garden::🏠🌼〰️⚓
:o:gate::🐘🤲🚪
:o:general::2?
:o:general1::♾️🤲
:o:general2::⚔️👥🤴🏻
:o:gentleman::🎩👨
:o:toget::📨🎬
:o:gift::🎁
:o:togive::✋️🎁🎬
:o:glad::😃
:o:glass::2?
:o:glass1::🍷〰️
:o:glass2::🍷🧱⭐
:o:togo::🚶🎬
:o:goat::🐐
:o:god::🙏⭐👆
:o:gold::2?
:o:gold1::👑🧱⭐
:o:gold2::Au
:o:good::2?
:o:good1::👍
:o:good2::👼🤲
:o:goodbye::👋💬🚶💨
:o:grandfather::👪👴
:o:grandmother::👪👵
:o:grass::🌿
:o:grave::2?
:o:grave1::☠⚓
:o:grave2::🏋️🤲
:o:great::2?
:o:great1::🐘🐘🤲
:o:great2::🌟👍
:o:green::🌿🎨
:o:gray::🐘🎨
:o:grey::🐘🎨
:o:ground::👣⬇️⚓
:o:group::👥
:o:togrow::🌳🤲↗️🎬
:o:gun::🔫⭐
:o:hair::🧒👌🌿
:o:half::1/2
:o:hall::🏠💦🐘🤲⚓
:o:hammer::🔨👌
:o:hand::✋️
:o:tohappen::🎬
:o:happy::😃
:o:hard::2?
:o:hard1::😧
:o:hard2::🧱👌🤲
:o:hat::👒
:o:hate::💢💢
:o:have::👜
:o:tohave::👜🎬
:o:he::👆🧒
:o:head::🧒👌
:o:healthy::👍🧍🤲
:o:tohear::👂🎬
:o:heavy::🏋️🤲
:o:heart::🧍❤️
:o:heaven::👼⚓
:o:height::🗼🤲⭐
:o:hello::👋💬
:o:help::🎁
:o:hen::🐤♀️
:o:her::👆🧒
:o:here::👇⚓
:o:hers::👆🧒
:o:tohide::🙈🔥🎬
:o:hide::🧍🌯⭐
:o:high::🗼🤲
:o:hill::🤏⛰️
:o:him::👆🧒
:o:his::👆🧒
:o:hit::💥🏁🎬
:o:hobby::😃🎁❗🎬
:o:hold::🤲👌🎬
:o:hole::🕳
:o:holiday::⛔⚠️🎬☀️🕒
:o:home::🏠❤️
:o:tohope::💖🔍💭🎬
:o:hope::💖🔍💭🎬
:o:horse::🐴
:o:hospital::🤒🌡️⚓
:o:hot::♨️🤲
:o:hotel::🤏🕒💰🔨🏠
:o:house::🏠
:o:how::3?
:o:how1::❓🔨
:o:how2::❓🤲
:o:how3::❓📏
:o:hundred::100
:o:hungry::🍽️⭐💖🤲
:o:hour::h
:o:tohurry::🏃🤲🎬
:o:husband::💑💍👨
:o:hurt::🤕🤲
:o:tohurt::2?
:o:tohurt1::🤕🔥🎬
:o:tohurt2::🤕🎬
:o:i::👈
:o:ice::🧊
:o:idea::💭➕💡
:o:if::➡⭐
:o:important::⚠️⚪🎬
;:o:in::⚓
:o:toincrease::📈🎬
:o:increase::📈
:o:inside::⏺️⚓
:o:become::✨
:o:into::2?
:o:into1::✨
:o:into2::⏺️📬
:o:tointroduce::💡🔥🎬
:o:introduction::💡🔥🎬
:o:invent::💭➕🧱🎬
:o:iron::Fe
:o:invite::👋
:o:is::📦
:o:island::🏝️
:o:it::👆
:o:its::👆
:o:jelly::🐢🤲💧
:o:job::⚠️🎬
:o:tojoin::👥✨🎬
:o:juice::🍎〰️💧
:o:tojump::🦘🎬
:o:just::4?
:o:just1::🌴
:o:just2::🤏⬅️🕒
:o:just3::⚖️⭐📖😃🤲
:o:just4::📏⭐🤲
:o:tokeep::🧵🤲🕒👜🎬
:o:key::2?
:o:key1::🔑
:o:key2::🎹💦
:o:tokill::☠️🔥🎬
:o:kind::2?
:o:kind1::👍👥🤲
:o:kind2::❓🤲⭐
:o:king::🤴🏻
:o:kitchen::🍳⚓
:o:knee::🦵🔗
:o:knife::🔪
:o:toknock::🚪🔊🎬
:o:toknow::💡🎬
:o:ladder::⬆️🚶🎬🔨⭐
:o:lady::✨⭐👩
:o:lamp::💡👌
:o:land::2?
:o:land1::🌊⚡️
:o:land2::🌍🏳️
:o:toland3::🛬🎬
:o:large::🐘🤲
:o:last::♾️⚖️➡️
:o:late::2?
:o:late1::➡️🕒🤲
:o:late2::☠️🤲
:o:lately::🤏⬅️🕒🤲
:o:laugh::😂
:o:lazy::🦥🤲
:o:tolead::🚶🔥🎬
:o:lead::Pb
:o:leaf::🍃
:o:tolearn::💡✨🎬
:o:toleave::🚶💨🎬
:o:leg::🦵
:o:left::2?
:o:left1::⬅️
:o:left2::⚓🎬
:o:tolend::🤏🕒✋️🎁🎬
:o:length::🧵🤲⭐
:o:less::⚖️🤏
:o:lesson::💡🔥🎬🕒
:o:let::🔥
:o:letter::2?
:o:letter1::🔤
:o:letter2::✉️📝
:o:library::📖⚓
:o:lie::✔️⚡️🤲💬
:o:tolie::2?
:o:tolie1::✔️⚡️🤲💬🎬
:o:tolie2::🛏🤲🧍🎬
:o:life::2?
:o:life1::🧒⌛
:o:life2::🐒〰️✖️🌼〰️
:o:light::2?
:o:light1::☀️⭐
:o:light2::🎈🤲
:o:tolight::🔥👌🎬
:o:like::2?
:o:like::🤲
:o:tolike::❤️🎬
:o:lion::🦁
:o:lip::👄💦
:o:tolist::🔢🤲📝🎬
:o:list::🔢🤲📝
:o:tolisten::👂🎬
:o:little::🤏
:o:tolive::2?
:o:tolive1::🏠🎬
:o:tolive2::🧒⌛🎬
:o:live3::📦
:o:lock::2?
:o:tolock1::🔒🎬
:o:lock2::🔒
:o:lonely::🌴🤲😥
:o:long::🧵🤲
:o:tolook::2?
:o:tolook1::👀🎬
:o:tolook2::🌟🎬
:o:lose::2?
:o:tolose1::⛔👜✨🎬
:o:tolose2::⚔️➡️👎🎬
:o:lot::❗❗
:o:tolove::❤️🎬
:o:love::❤️
:o:low::🗼⚡️🤲
:o:lower::⚖️🗼⚡️🤲
:o:tolower::↘️🔥🎬
:o:luck::☘️⭐
:o:machine::⚙️⭐
:o:main::♾️⚖️🐘🤲💦
:o:tomake::🧱🎬
:o:male::♂️
:o:man::👨
:o:many::❗❗
:o:map::🗺️
:o:mark::❌👌〰️
:o:market::🔄✋️🎁🎬
:o:tomarry::💑💍🎬
:o:matter::2?
:o:matter1::💭❗
:o:matter2::🧱⭐
:o:may::2?
:o:may1::🤔
:o:may2::👍
:o:me::👈
:o:meal::🍽️⭐
:o:tomean::💭🔥🎬
:o:mean::😠
:o:tomeasure::📏🎬
:o:measure::1?
:o:measure1::🔨⭐
:o:measure2::📏⭐
:o:meat::🍖
:o:medicine::2?
:o:medicine1::⚕️
:o:medicine2::⚕️❗
:o:tomeet::👥✨🎬
:o:member::👥💦🧒
:o:tomention::💬🎬
:o:method::🔨⭐
:o:middle::2?
:o:middle1::⏺️⚓🤲
:o:middle2::⏺️⚓🤲⭐
:o:milk::🐄🥛
:o:million::10^6
:o:mind::🧒💭
:o:minute::min
:o:miss::2?
:o:tomiss1::⛔🎯🎬
:o:tomiss2::⛔👇⚓💡😥🎬
:o:miss::✨⭐👧
:o:mistake::🙃👎
:o:tomix::🌀🎬
:o:model::🤏🗿〰️
:o:tomodel::🤏🗿〰️🎬
:o:modern::👇⌛🤲
:o:moment::🕒💦❗
:o:money::💰
:o:monkey::🐒
:o:month::🌙⌛
:o:moon::🌙
:o:more::2?
:o:more1::⚖️
:o:more2::➕🤲
:o:morning::☀️↗️🕒
:o:most::3?
:o:most1::♾️⚖️
:o:most2::♾️⚪🤲
:o:most3::♾️⚖️⬆️🤲
:o:mother::👪👩
:o:mountain::⛰️
:o:mouth::👄
:o:tomove::2?
:o:tomove1::🧍👋🎬
:o:tomove2::👋🎬
:o:move::🧍👋⭐
:o:much::❗❗
:o:music::🎵
:o:must::⚠️
:o:my::👈
:o:name::📣❗
:o:narrow::🤏🚪🤲
:o:nation::🌍🏳️
:o:nature::2?
:o:nature1::🌳⭐
:o:nature2::✔️🤲📦⭐
:o:near::👇⚪⚓
:o:nearly::📬⚪🎬🤲
:o:neck::🦢💦❗
:o:toneed::👜⚠️🎬
:o:need::👜⚠️🎬❗
:o:needle::📌🤲❗
:o:neighbour::⚓⚪🤲🧒
:o:net::🕸️〰️
:o:new::1.🕒🤲
:o:news::📰⭐
:o:newspaper::📰
:o:next::➡️🤲
:o:nice::👍
:o:night::🌙🕒
:o:nine::9
:o:no::🙅
:o:noble::✨⭐
:o:noise::🔊
:o:none::⛔❗
;:o:nor::
:o:north::🧭⬆️
:o:nose::👃
:o:not::⛔
:o:nothing::⛔❗
:o:tonotice::💡✨🎬
:o:notice::💡🔥🎬📝
:o:now::👇🕒
:o:number::🔢
:o:toobey::👍🐶🎬
:o:object::2?
:o:object1::🔍⭐
:o:object2::❗
:o:toobject::🙅🎬
:o:ocean::🌊⚓
;:o:of::
;:o:off::
:o:offer::👋⭐
:o:tooffer::👋⭐🎬
:o:office::⚠️🎬⚓
:o:often::❗❗🕒
:o:oil::🛢️💧
:o:old::👴🤲
;:o:on:
:o:one::1
:o:only::🌴
:o:toopen::🔓🎬
:o:open::🔓🤲
:o:opposite::2?
:o:opposite1::⚡️🤲
:o:opposite2::⚡️
:o:or::✖️
:o:orange::2?
:o:orange1::🍑⚪
:o:orange2::🍑🎨
:o:toorder::2?
:o:toorder::▶️🔥🎬
:o:toorder::🔢🤲🔥🎬
:o:other::🔀
:o:our::👈👈
;:o:out::
:o:outside::⏺️⚡️
:o:over::⬆️⚓
:o:toown::👜🎬
:o:own::👜🤲
:o:page::📝👌
:o:pain::🤕❤️⭐
:o:topaint::🎨🎬
:o:paint::🎨💧
:o:pair::2🧒👥
:o:pan::🍳
:o:paper::2?
:o:paper1::📝
:o:paper2::📝🧱⭐
:o:parent::👪🧍
:o:park::🌳⚓
:o:part::💦
:o:partner::👥🧒
:o:party::2?
:o:party1::🎉🕒
:o:party2::👥
:o:topass::3?
:o:topass1::⛔🎬
:o:topass2::🔀🧒✋️🎁🎬
:o:topass3::🚶➕👀🎬
:o:pass::🚪⭐
:o:past::⬅️🕒
:o:path::🚶⚓
:o:topay::💰✋️🎁🎬
:o:peace::🕊️⭐
:o:pen::🖊️
:o:pencil::✏️
:o:people::👥
:o:pepper::2?
:o:pepper1::🌶️
:o:pepper2::🌶️🤲🧂
:o:per::➗
:o:perfect::💯🤲
:o:period::3?
:o:period1::⌛
:o:period2::⏺️👌
:o:period3::👩🔄🕒
:o:person::🧒
:o:petrol::🚗⛽💧
:o:photograph::⚙️⭐🖼️
:o:photo::⚙️⭐🖼️
:o:piano::🎹
:o:topick::✖️🎬
:o:pick::⛏️
:o:picture::🖼️
:o:piece::💦
:o:pig::🐷
:o:pink::🐷🎨
:o:place::⚓
:o:plane::2?
:o:plane1::✈️
:o:plane2::📝🤲
:o:plant::🌼〰️
:o:plastic::🛢️💧🧱⭐
:o:plate::🍽️➖🍴
:o:toplay::🎮🎬
:o:play::🎭
:o:please::🙏
:o:pleased::😃
:o:plenty::❗❗
:o:pocket::👚⭐👜👌
:o:point::2?
:o:point1::⏺️👌
:o:point2::💯〰️🔢
:o:topoint::☝️👌🎬
:o:poison::☠️💧
:o:police::👮‍⭐
:o:polite::👥🎁⚠️🎬
:o:pool::💧🕳
:o:poor::⛔💰👜
:o:popular::🧒🧒☝️❤️🎬
:o:position::2?
:o:position1::⚓
:o:position2::❓🤲⭐
:o:possible::💪📦
:o:potato::🥔
:o:topour::⏺️💧🎬
:o:power::💪⭐
:o:present::2?
:o:present1::🎁
:o:present2::👇🕒
:o:topresent::👀🔥🎬
:o:topress::✊️👌🎬
:o:press::📰👥
:o:pretty::✨⭐👀🤲
:o:toprevent::⚡️🔥🎬
:o:price::⚠️💰
:o:prince::🤴🏻👪👦
:o:prison::🚶💨⛔💪🎬⚓
:o:private::🌴🌴👥🎁
:o:prize::🥈
:o:probably::🤔🤔🤲
:o:problem::2?
:o:problem1::😟❗
:o:problem2::💭⚠️🎬❗
:o:toproduce::🧱🎬
:o:produce::🧱🎬❗
:o:topromise::❗🚶⭐💬🎬
:o:promise::❗🚶⭐🎬💬
:o:proper::⚠️🎬
:o:toprotect::🛡️🎬
:o:toprovide::✋️🎁🎬
:o:public::♾️🧒🎁
:o:topull::🧵🤲✋️⬇️🎬
:o:topunish::🥈⚡️🎬
:o:pupil::💡✨🧒
:o:topush::💨✋️🎬
:o:toput::⬇️✋️🎬
:o:queen::👑👩
:o:toquestion::"❓"💬🎬
:o:question::"❓"💬
:o:quick::🏃💨🤲
:o:quiet::🤫
:o:quite::➕➖
:o:radio::🎙️📻
:o:rain::🌧️
:o:rainy::🌧️🤲
:o:toraise::↗️🔥🎬
:o:toreach::🏁📬🚶🎬
:o:reach::🚶🎬⚪⚓
:o:toread::📖🎬
:o:ready::💪🎬
:o:real::⛔💭👀🤲
:o:really::✔️🤲
:o:toreceive::📨🎬
:o:torecord::👀〰️➕✍️🎬
:o:record::2?
:o:record1::👀〰️📝
:o:record2::♾️⚖️⬆️🤲
:o:red::❤️🎨
:o:toremember::🧒👌✍️🎬
:o:toremind::💭🔥🎬
:o:toremove::🚶💨🔥🎬
:o:torent::🤏🕒📨🎬
:o:rent::🤏🕒📨🎬💰
:o:torepair::🔧🎬
:o:torepeat::↩️🕒❗🎬
:o:toreply::↩️🤲💬🎬
:o:toreport::👀〰️➕💬🎬
:o:report::👀〰️💬
:o:rest::2?
:o:rest1::🔀❗
:o:rest2::➖🎬➡❗
:o:torest::🦥🎬
:o:restaurant::💰🔨🍽️⭐🎬⚓
:o:result::🔥⭐
:o:toreturn::2?
:o:toreturn1::↩️🤲✋️🎁🎬
:o:toreturn2::↩️🤲🚶🎬
:o:rice::🌾⛲🍙⭐
:o:rich::2?
:o:rich1::❗❗👜🤲
:o:rich2::💰👜🤲
:o:toride::🐴🎬
:o:right::3?
:o:right1::➡️
:o:right2::✔️🤲
:o:right3::⚖️⭐📖🔨⭐
:o:ring::💍
:o:toring::🔊🎬
:o:torise::↗️🎬
:o:road::2?
:o:road1::🚶⚓
:o:road2::🚗⚓
:o:torob::🙅🤲✋️👜🎬
:o:rock::🧱👌〰️
:o:room::🏠📦⭐
:o:round::⚪👌🤲
:o:rubber::🚗🎡⭐🧱⭐
:o:rude::👥🎁⚠️🎬⚡️🤲
:o:torule::🤴🏻🎬
:o:rule::3?
:o:rule1::🤴🏻🎬
:o:rule2::♾️🕒✔️🤲❗
:o:rule3::⚖️⭐📖💦
:o:ruler::2?
:o:ruler1::📏👌
:o:ruler2::🤴🏻🎬🧒
:o:torun::🏃🎬
:o:torush::🏃💨🤲🎬
:o:rush::🏃💨
:o:sad::😥
:o:safe::⚠️⭐⚡️
:o:tosail::💨🚢🎬
:o:sail::💨🚢🎁📝
:o:salt::🧂
:o:same::=
:o:sand::🐫🧂⭐
:o:tosave::3?
:o:tosave1::⚠️⭐✊🎬
:o:tosave2::⛔🔨🎬
:o:tosave3::💾🎬
:o:tosay::💬🎬
:o:school::🏫
:o:science::⚗️⭐
:o:scissors::✂️
:o:tosearch::🔍🎬
:o:seat::🪑〰️
:o:second::2?
:o:second1::2.
:o:second2::s
:o:tosee::👀🎬
:o:toseem::🌟🎬
:o:tosell::💰🔀✋️🎁🎬
:o:tosend::📩🎬
:o:sentence::📝〰️👌
:o:tosentence::⚖️⭐📖✖️🎬
:o:toserve::🐶🎬
:o:seven::7
:o:several::>1
:o:sex::2?
:o:sex1::♂️♀️〰️
:o:sex2::🍆⭐🎬
:o:shade::☀️🕳👌
:o:shadow::☀️🕳👌
:o:toshake::👋🎬
:o:shape::👤⭐
:o:toshare::💦🔍✋️🎁🎬
:o:sharp::👍🔪🤲
:o:she::👆👩
:o:sheep::🐑
:o:sheet::2?
:o:sheet1::📝
:o:sheet2::🛏💦📝
:o:shelf::📝🤲🌳🧱❗
:o:toshine::🌟👌🎬
:o:ship::🚢
:o:toship::🚚🎬
:o:shoe::👠〰️
:o:toshoot::🔫⭐🎬
:o:toshop::🛍️🎬
:o:shop::💰🔨📨🎬🏠
:o:short::🧵⚡️🤲
:o:should::2?
:o:should1::☝️
:o:should2::🤔🤔
:o:shoulder::👤💦⬇️
:o:toshout::📣🎬
:o:toshow::👀🔥🎬
:o:sick::🤒🌡️🤲
:o:side::🧍⬇️💦
:o:tosignal::💡🔥👋🎬
:o:signal::📶⭐
:o:silence::⛔🔊
:o:silly::🤡🤲
:o:silver::Ag
:o:similar::🤲
:o:simple::💡🙂🤲
:o:single::🌴1
:o:since::⛲
:o:tosing::🎵💬🎬
:o:tosink::2?
:o:tosink1::⬇️🚶🎬
:o:tosink2::↘️🔥🎬
:o:sink::💧🛁〰️
:o:sister::👪🧒➕👧
:o:tosit::🪑🎬
:o:six::6
:o:size::🐘🤲⭐
:o:skill::🎬🔍💡🎬❗
:o:skin::🧍🌯⭐
:o:skirt::👗💦⬇️
:o:sky::☁️⚓
:o:tosleep::💤🎬
:o:sleep::💤
:o:toslip::2?
:o:toslip1::⛸️🤲🎬
:o:toslip2::⚓📬✋️⬇️🎬
:o:slow::🐢🤲
:o:small::🐭🤲
:o:smell::2?
:o:tosmell1::👃🎬
:o:tosmell2::❓👃🎬
:o:smell::💩🤲💨
:o:tosmile::🙂🎬
:o:smile::🙂
:o:smoke::🔥👌💨
:o:tosmoke::🚬🎬
:o:snow::🌨️❄️
;:o:so::
:o:soap::🧼💧
:o:sock::1🧦
:o:soft::🧈🤲
:o:some::❗
:o:someone::🧒
:o:something::❗
:o:sometimes::🌴🌴🕒
:o:son::👪👦
:o:soon::🤏➡️🕒
:o:sorry::2?
:o:sorry1::🙇
:o:sorry2::🥺
:o:sound::2?
:o:sound1::🔊
:o:sound2::👍
:o:soup::💧🤲🍽️⭐
:o:south::🧭⬇️
:o:space::2?
:o:space1::🔓🤲⚓
:o:space2::♾️🌟⚓
:o:speak::💬🎬
:o:special::♾️⚪⚡️🤲
:o:speed::🏃💨🤲⭐
:o:tospell::🔤🎬
:o:spell::🧙‍🎬
:o:spend::🔨🎬
:o:spoon::🥄
:o:sport::🎾⭐
:o:tospread::2?
:o:tospread1::❗❗⚓🔥🎬
:o:tospread2::🔓🎬
:o:spring::🌼🎬🕒
:o:square::🔲
:o:stamp::✉🎁🔲
:o:tostand::🧍🎬
:o:stand::🧍🎬⚓
:o:star::🌟
:o:start::⛲
:o:station::⚓
:o:tostay::⚓🎬
:o:tosteal::🤫✋️👜🎬
:o:steam::💧🌫️
:o:tostep1::🚶🦶🎬
:o:step::2?
:o:step1::🚶🦶
:o:step2::🔀🧬
:o:still::2?
:o:still1::👇🕒📬
:o:still2::👇🕒⛲
:o:stomach::🧍⏺️👜👌
:o:stone::🥌〰️
:o:stop::🛑
:o:tostore::📚〰️🎬
:o:store::📚〰️🎬⚓
:o:storm::🌧️💨
:o:story::💬💬
:o:strange::⛔♾️🤲
:o:street::🚶⚓
:o:strong::💪🤲
:o:structure::🏠⭐
:o:student::💡✨🎬🧒
:o:tostudy::💡✨🎬
:o:stupid::🧒👌👎🤲
:o:subject::2?
:o:subject1::☝️💬💦
:o:subject2::💭❗
:o:substance::🧱⭐
:o:successful::🏁📬🚶
:o:success::🏁📬🚶
;:o:such::
:o:sudden::😮🕒🤲
:o:sugar::🍭🧂
:o:suitable::👍👥🤲
:o:summer::♾️⚖️♨️🕒
:o:sun::☀️
:o:sunny::☀️🤲
:o:tosupport::🎁🎬
:o:sure::💡🎬🤲
:o:surprise::😮
:o:sweet::🍭🤲
:o:toswim::🐟🎬
:o:sword::1⚔️👌
:o:table::🪑➕❗
:o:totake::✋️👜🎬
:o:totalk::💬🎬
:o:tall::🗼🤲
:o:totaste::👅⭐🎬
:o:taste::👅⭐
:o:taxi::💰🔨🚶🔥🚕
:o:toteach::💡🔥🎬
:o:team::👥
:o:tear::🧵🤲✋️⬇️🎬
:o:telephone::☎️
:o:television::📺
:o:totell::💬🎬
:o:ten::10
:o:tennis::🎾
:o:terrible::😱🔥🎬
:o:test::👀⭐
:o:than::⚖️
:o:that::👆
:o:the::👇
:o:their::👆👥
:o:then::➡️
:o:there::👆⚓
:o:therefore::👇💡
:o:these::👇👇
:o:thick::🐋🤲
:o:thin::📝👌🤲
:o:thing::❗
:o:third::2?
:o:third1::3.
:o:third2::1/3
:o:this::👇
:o:though::⚡️
:o:threat::⚠️⭐
:o:three::3
:o:totidy::💧🧽🎬
:o:tidy::💧🧽🎬🤲
:o:totie::🔗🎬
:o:tie::2?
:o:tie1::👔
:o:tie2::⚔️➡=
:o:title::🐘🤲❓📣
;:o:to::
:o:today::👇☀️🕒
:o:toe::👣💦☝️👌
:o:together::👥🤲
:o:tomorrow::➡️☀️🕒
:o:tonight::➡️🌙🕒
:o:too::2?
:o:too1::🤯
:o:too2::➕
:o:tool::🔨〰️
:o:tooth::🦷
:o:top::⬆️💦
:o:total::♾️
:o:totouch::✋️🎬
:o:touch::✋️⭐
:o:town::🏠🏠⚓
:o:totrain::💡✨🔥🎬
:o:train::🚂
:o:tram::🚋
:o:totravel::🔀⚓📬🚶🎬
:o:tree::🌳
:o:trouble::👎❗
:o:true::✔️🤲
:o:totrust::🧍❤️🔨💡🎬
:o:twice::2❌🔢
;:o:try::👀⭐
:o:toturn::🏁🔀🎬
:o:turn::▶️☝️🎬❗
:o:type::📦⭐
:o:totype::⌨️🎬
:o:ugly::👀👎
:o:uncle::👪🧍➕👨
:o:under::⬇️⚓
:o:understand::2?
:o:tounderstand1::👀〰️➡💡🎬
:o:tounderstand2::💡💡🎬
:o:unit::2?
:o:unit1::1📏
:o:unit2::1💦
:o:until::📬
:o:up::⬆️
:o:touse::🔨🎬
:o:useful::🔨💪🎬
:o:usual::♾️⚪🤲
:o:usually::♾️⚪🤲
:o:vegetable::🥕〰️
:o:very::❗❗🤲
:o:village::🤏🏘️
:o:voice::🧒📣💪
:o:tovisit::🚶➕👀🎬
:o:towait::🧵🤲🕒🧍🎬
:o:towake::2?
:o:towake1::⛔💤🔥🎬
:o:towake2::⛔💤✨🎬
:o:towalk::🚶🎬
:o:want::💖
:o:warm::🤏♨️🤲
:o:was::📦
:o:towash::💧🧽🎬
:o:waste::🗑️⭐
:o:towatch::👀🎬
:o:watch::⌚
:o:water::💧
:o:way::2?
:o:way1::🚶⚓
:o:way2::🔨⭐
:o:we::👈👈
:o:weak::💪⚡️🤲
:o:towear::2?
:o:towear1::👚🎬
:o:towear2::👴🤲🔥🎬
:o:weather::☀️✖️🌧
:o:wedding::💑💍💒
:o:week::7☀️🕒
:o:weight::🏋️🤲⭐
:o:welcome::👍🚶🎬
:o:towelcome::👋⭐🎬
:o:were::📦
:o:west::⬅️🧭
:o:wet::💧👜
:o:what::❓
:o:wheel::🎡⭐
:o:when::❓🕒
:o:where::❓⚓
:o:which::❓
:o:while::🕒
:o:white::👰🏻🎨
:o:who::❓🧒
:o:why::❓💡
:o:wide::🧵🤲
:o:wife::💑💍👩
:o:wild::🦁🌳🤲
:o:towin::⚔️➡️👍🎬
:o:win::⚔️➡️👍
:o:wind::💨
:o:window::🏠👁️
:o:wine::🍷
:o:winter::⛄️🕒
:o:wire::☎️🧵
:o:wise::🧙🏻🤲
:o:wish::💖⭐
:o:with::➕
:o:without::➖
:o:woman::👩
:o:towonder::⛔💡🎬
:o:wonder::✨😲
:o:word::💬💦
:o:towork::4?
:o:towork1::💰🎁❗🎬
:o:towork2::🧒💦👌❗🎬
:o:towork3::👋🎬
:o:towork4::👍⭐🎬
:o:work::🧱🎬❗
:o:world::3?
:o:world1::🌍
:o:world2::🌏
:o:world3::🌎
:o:toworry::😟🎬
:o:yard::🐘🤲⚓
:o:toyell:📣🎬
:o:yesterday::⬅️☀️🕒
:o:yet::2?
:o:yet1::⛔👇🕒
:o:yet2::👇🕒📬
:o:you::👉
:o:young::👶🤲
:o:your::👉
:o:zero::0
:o:zoo::🐒🐒〰️⚓
:o:email::💻⭐✉️
:o:mail::✉️⭐
:o:pony::🤏🐴
:o:idiocy::🧒👌👎❗
:o:idiot::🧒👌👎🧒
:o:hi::👋💬
:o:surprising::😮🤲
:o:pillow::🛏️👛
:o:translator::💬🔨⭐🔀🎬🧒
:o:totranslate::💬🔨⭐🔀🎬
:o:health::👍🧍⭐
:o:comic::2?
:o:comic1::😂🔥🎬
:o:comic2::🖼️💬💬
:o:napalm::🩹🤲🔥👌
:o:channel::🌊🎬⚓
:o:chatroom::🤏💬📦⭐
:o:chat::🤏💬
:o:server::🔗🔥🎬💻〰️
;:o:settings::
;:o:setting::
:o:panter::🐆
:o:leopard::🐆
:o:hollow::🐚🤲
:o:toview::👀🎬
:o:shallow::🕳⚡️🤲
:o:purple::🍆🎨
:o:background::🚶➡⚓
:o:foreground::➡🚶⚓
:o:trackball::🖲️
:o:alphabet::♾️🔤
:o:reference::👀🔥🎬❗
:o:torefer::☝️👌🎬
:o:style::🔨⭐
:o:hairstyle::🧒👌🌿🔨⭐
:o:screwdriver::🌀🤲📌🔨〰️
:o:app::💻〰️🔨⭐
:o:program::💻〰📝
:o:code::2?
:o:code1::🤫🤲💬
:o:code3::💻〰️📝
:o:tocode::💻〰️📝🎬
:o:screen::🖥️
:o:kickscooter::🛴
:o:wheelchair::🦽
:o:motorscooter::🛵
:o:autorickshaw::🛺
:o:lorry::🚚
:o:transporter::🚚
:o:totransport::🚚🎬
:o:creator::🧱🎬🧒
:o:tocreate::🧱🎬
:o:tray::📝🤲❗
:o:todoubt::🙅🤲🔍💭🎬
:o:indecisive::⛔✖️🎬
:o:indecision::⛔✖️🎬
:o:confident::💪⭐💭🤲
:o:confidence::💪⭐💭
:o:boardgame::📝🤲🎮⭐
:o:punctuation::❓👌〰️
:o:particle::2?
:o:particle1::🤏❗
:o:particle2::🤏💬💦
:o:noun::❗💬💦
:o:adjective::🤲💬💦
:o:verb::🎬💬💦
:o:menstruation::👩❤️💦👌🎬
:o:tomenstruate::👩❤️💦👌🎬
:o:erection::2?
:o:erection1::🧱🎬
:o:erection2::🍆⭐🧍🎬
:o:ejaculation::🍆⭐💦🎬
:o:toejaculate::🍆⭐💦🎬
:o:todiscuss::🔥💬🎬
:o:discussion::🔥💬
:o:dirt::💩🤲❗
:o:mud::💩🤲❗
:o:bald::⛔🧒👌🌿🤲
:o:prayerbeads::📿
:o:jewel::💎〰️
:o:jewelry::💎〰️
:o:torot::💩✨🎬
:o:rotten::💩✨🎬🤲
:o:toswell::🐘🤲✨🎬
:o:tosew::🧵🎬
:o:towipe::👋🤲✋️🎬
:o:tosqueeze::🧽🤏🎬
:o:flute::🎵💨🎬📏〰️
:o:accordeon::💨🎬🎹
:o:instrument::3?
:o:instrument1::🎹〰️
:o:instrument2::🔨〰️
:o:instrument3::🔨⭐
:o:accordeon::💨✋️🎬🎹〰️
:o:tosuck::🥤🎬
:o:guts::🧍⏺️⚓❗
:o:fingernail::☝️👌📌
:o:trail::🚶⚓
:o:urn::⚱️
:o:ash::🔥👌🧂⭐
:o:liver::🍶〰🎁🧍⏺️⚓❗
:o:organ::3?
:o:organ1::💦🔨〰️
:o:organ2::🧍⏺️🔨〰️
:o:organ3::⛪🎹
:o:tail::🦨⬆️⚓
:o:otter::🦦
:o:raccoon::🦝
:o:scorpion::🦂
:o:skunk::🦨
:o:grease::🥩💦👰🏻🎨
:o:tobark::🔊🎬
:o:bark::🌳🌯⭐
:o:root::🌳🦶
:o:suitcase::🧳
:o:luggage::🧳
:o:baggage::🧳
:o:trunk::2?
:o:trunk1::🌳🧍
:o:trunk2::🚗💼
:o:louse::🧒👌🌿🐞〰️
:o:state::2?
:o:state1::❓🤲⭐
:o:state2::🌍🏳️
:o:company::🔗👥
:o:organization::🔗👥
:o:bond::🔗
:o:republic::♾️🧒🎁🤴🏻👥
:o:stability::⛔🔀⭐
:o:stable::⛔🔀🎬🤲
:o:toroar::🦁📣🎬
:o:trap::🕸️⭐
:o:breast::2?
:o:breast1::👩🍈⭐
:o:breast2::🧍⬆️💦
:o:melon::🍈
:o:randomness::🎲⭐
:o:random::🎲🤲
:o:remedy::🤕✊️❗
:o:bee::🐝
:o:tocast::🏀🎬
:o:toseek::🔍🎬
:o:friendly::👍👥🤲
:o:probability::🤔🔢
:o:cowboy::🤠
:o:telescope::🔭
:o:footprint::🐾
:o:footprints::🐾
:o:poodle::🐩
:o:boar::🐗
:o:chick::🐤
:o:chicklet::🐤
:o:ram::🐏
:o:almost::🤏😧🤲
:o:barely::🤏🙂🤲
:o:fur::🐺〰️🌯⭐
:o:wrapping::🌯⭐
:o:hidden::⛔👀💪🎬
:o:tohandover::✋️🎁🎬
:o:vigilant::👀🛡️🎬
:o:transformation::✨
:o:mutation::✨
:o:tocopy::🤲🔥🎬
:o:copy::🤲🔥🎬❗
:o:gorilla::🦍
:o:crocodile::🐊
:o:giraffe::🦒
:o:honorable::✨⭐
:o:tocondemn::👎💬🎬
:o:tojourney::🔀⚓📬🚶🎬
:o:journey::🔀⚓📬🚶🎬
:o:hunter::🏹🧒
:o:fisher::🎣🧒
:o:tohaunt::👻🎬
:o:haunted::👻🤲
:o:farmhouse::🍽️⭐🌾🏠
:o:sleeping::💤
:o:stupidity::🧒👌👎
:o:sparkly::✨👌
:o:shiny::✨👌
:o:sadness::😥
:o:tomelt::🔥💦🎬
:o:heatwave::☀️♨️
:o:sunbeam::☀️🔱
:o:sunray::☀️🔱
:o:sunlight::☀️🔱
:o:horror::😨
:o:todread::😨🎬
:o:dread::😨
:o:technology::⚙️⭐
:o:delight::😃
:o:hatred::😠💢
:o:wrath::😠💢
:o:sacrifice::✋️🎁
:o:tocamp::🎪🎬
:o:camp::🎪🎪〰️
:o:universal::♾️🎁
:o:shortcut::🧵⚡️🤲🚶⚓
:o:basis::👣⬇️⚓
:o:foundation::👣⬇️⚓
:o:cable::🔌〰️👌
:o:toenclose::🔲🎬
:o:tosurround::🔲🎬
:o:toencircle::⚪👌🎬
:o:cell::2?
:o:cell1::🔲🎬⚓
:o:cell2::🧍🤏🔲
:o:flesh::🧍🧱⭐
:o:religion::🙏⭐💭
:o:bible::🙏⭐📖
:o:spacious::❗❗⚓🤲
:o:concise::🤏💬🤲
:o:terse::🤏💬🤲
:o:verbose::💬💬🤲
:o:eloquent::👍💬🤲
:o:brutal::👊🤲
:o:plasma::⚡️👌🧱⭐
:o:sticker::🩹🎬🤏📝
:o:chapter::👣💬💦
:o:section::👣💬💦
:o:imagination::💭👀🎬
:o:illusion::💭🌍
:o:fantasy::💭🌍
:o:reality::⛔💭🌍
:o:alternate::🔀
:o:livingroom::🏠💦🧒⌛🎬⚓
:o:bathroom::🛀⚓
:o:restroom::🛀⚓
:o:bar::2?
:o:bar1::🍶〰️⚓
:o:bar2::📏〰️
:o:genie::🧞
:o:pie::🥧
:o:toexile::🚶💨🔥🎬
:o:exile::🚶💨📬⚓
:o:ink::✍️🎬💧
:o:todye::🎨🎬
:o:dye::🎨💧
:o:tostrike::💥🏁🎬
:o:goblin::🤏👿
:o:tengu::👺
:o:shinto::⛩️⭐
:o:shintou::⛩️⭐
:o:sikh::👳
:o:shrine::🤏⛪
:o:chapel::🤏⛪
:o:muslim::☪️🤲
:o:toapproach::=⚓✨🎬
:o:approach::🔨⭐
:o:ogre::👹
:o:demon::👹
:o:toexhaust::🔨📬🎬
:o:exhausted::2?
:o:exhausted1::😩
:o:exhausted2::🔨📬🎬🤲
:o:replica::=🤲🧱🎬❗
:o:password::🔒💬
:o:possibly::🤔🤲
:o:emotion::❤️⭐
:o:wow::🤩
:o:masterpiece::🧐⭐❗
:o:assistant::🎁🎬🧒
:o:toassist::🎁🎬
:o:favorite::♾️⚖❤️🎬
:o:trick::🧐🔨⭐
:o:unthinkable::💭⛔💪🎬
:o:incredible::✔️🤲🔍💭⛔💪🎬
:o:unimaginable::👀💭⛔💪🎬
:o:bandit::🙅🤲✋️👜🎬🧒
:o:pirate::☠️🚢🧒
:o:hibiscus::🌺
:o:cherryblossom::🌸
:o:sakura::🌸
:o:genius::2?
:o:genius1::😮💡✨🎬🧒
:o:genius2::😮💡✨🎬
:o:insight::😮💡✨🎬❗
:o:todeactivate::⛔▶️🔥🎬
:o:toactivate::▶️🔥🎬
:o:tospeculate::🤔🎬
:o:tosuspect::🤔🎬
:o:tospoil::👎🔥🎬
:o:tohug::🤗🎬
:o:toembrace::🤗🎬
:o:opportunity::💪🎬🕒
:o:obstacle::🚧⭐
:o:wide::🍃🤲
:o:amount::🔢
:o:awesome::😆👍
:o:insufficient::👎⚪
:o:kraken::🐙
:o:monster::🧟〰️
:o:toavoid::⛔✋️⭐🏁🎬
:o:tocontact::✋️🎬
:o:contact::✋️🎬
:o:torecognize::2?
:o:torecognize1::❓📦💡🎬
:o:torecognize2::✔️🤲📦💭🎬
:o:toguide::🚶🔥🎬
:o:guide::2?
:o:guide1::🚶🔥🎬🧒
:o:guide2::💡🔥🎬📖
:o:torch::2?
:o:torch1::🔥📏〰️
:o:torch2::🔦
:o:match::4?
:o:match1::👥🔥🎬
:o:match2::=🔥🎬
:o:match3::⚔️🎬➡️👍✖️👎
:o:match4::🤏🔥📏〰️
:o:contest::⚔️🎬➡️👍✖️👎
:o:tocompete::⚔️🎬➡️👍✖️👎🎬
:o:competition::⚔️🎬➡️👍✖️👎
:o:crisis::⚠️⭐🕒
:o:takeout::🥡
:o:falafel::🧆
:o:benefactor::✋️🎁🎬🧒
:o:treat::🎬
:o:haughty::↩️🧍♾️⚖️👍💭🎬
:o:arrogant::↩️🧍♾️⚖️👍💭🎬
:o:proud::↩️🧍✨⭐💭🎬
:o:todisturb::2?
:o:todisturb1::🛑🔥🎬
:o:todisturb2::💢🔥🎬
:o:toaccept::🤝⭐🎬
:o:toinsist::🙅🔍⛔👂🏁🎬
:o:tractor::🌾🚗
:o:warehouse::📚〰️🎬🏠
:o:storehouse::📚〰️🎬🏠
:o:decision::✖️🎬
:o:history::⬅️🕒💭💬💬
:o:uncertain::⛔💡🎬🤲
:o:project::🎬
:o:toproject::📽️🎬
:o:projector::📽️
:o:frame::2?
:o:frame1::🎞️
:o:frame2::🖼️💦🔲
:o:filmframe::🎞️
:o:tofell::🪓🎬
:o:element::♾️⚖️🤏💦
:o:particular::💦🤲
:o:obedient::👍🐶🤲
:o:waiter::🍽️⭐✋️🎁🎬🧒
:o:chicken::🐔
:o:llama::🦙
:o:topretend::🎭🤲🎬
:o:complex::❗❗💦📦
:o:situation::❓🤲⭐
:o:bass::🐘🤲🎻
:o:existence::📦
:o:measurement::📏⭐
:o:funeral::🕳📬⚰️🎬
:o:ceremony::📏⭐🤲🎬❗
:o:injustice::⚖️⭐⚡️
:o:verdict::⚖️⭐🎬
:o:comparison::⚖️🎬
:o:similarity::🤲⭐
:o:passive::🔍🤲
:o:disastrous::👎👎
:o:catastrophic::👎👎
:o:milliliter::mL
:o:liter::L
:o:gramm::g
:o:kilogramm::kg
:o:meter::m
:o:fullmoon::⚪👌🌙
:o:fleurdelis::⚜️
:o:torecycle::♻️🎬
:o:recycling::♻️
:o:registered::®️
:o:copyright::©️
:o:trademark::™️
:o:informationsign::ℹ️
:o:id::🆔
:o:joystick::🕹️
:o:playbutton::▶️
:o:reload::🔄
:o:nexttrack::⏭️
:o:fromto::➡️
:o:fastforward::⏩
:o:obvious::💡🙂🎬
:o:nightmare::💤👎💭👀
:o:yinyang::☯
:o:redlantern::🏮
:o:entire::♾💦🤲
:o:injection::💉⭐
:o:toinject::💉🎬
:o:toignore::⛔👀🏁🎬
:o:deed::▶️🎬
:o:action::🎬
:o:mobilephone::📱
:o:cellphone::📱
:o:smartphone::📱
:o:topierce::📌🎬
:o:roof::🏠👒
:o:claw::🦞✋️
:o:toscratch::🦞🎬
:o:itch::🦞🔥🎬🧍⚓
:o:itchy::🦞🔥🎬
:o:rub::👋🤲✋️🎬
:o:feedback::↩️🤲💡🔥🎬❗
:o:experience::👀〰️🎬
:o:reaction::↩️🤲🎬❗
:o:toreact::↩️🤲🎬
:o:morals::👍✖️👎💡
:o:ethics::👍✖️👎💡
:o:chef::🍳🧒
:o:cook::🍳🧒
:o:chief::🤴🏻🎬🧒
:o:boss::🤴🏻🎬🧒
:o:captain::🚢🤴🏻
:o:ok::👍⚪
:o:alright::👍⚪
:o:thief::🤫✋️👜🎬🧒
:o:tobury::🕳📬⚰️〰️🎬
:o:rust::❤️🎨⚓👌🧱⭐
:o:screw::🌀🤲📌⭐
:o:assign::✋️🎁🎬
:o:opponent::⚡️🤲🧒
:o:toblame::👎🔍✋️🎁🎬
:o:guilt::👎🧒📦
:o:concern::🔗⭐
:o:relation::🔗⭐
:o:thought::💭
:o:soul::🧒💦👻
:o:toprotest::✊️💬🎬
:o:tobadmouth::👎💬🎬
:o:stream::🌊🎬⚓
:o:task::⚠️🎬❗
:o:mission::⚠️🎬❗
:o:chaotic::🌀🤲
:o:chaos::🌀⭐
:o:player::2?
:o:player1::🎮🧒
:o:player2::🎭🧒
:o:sofa::🛏🤲🪑
:o:couch::🛏🤲🪑
:o:coach::💡🔥🎬🧒
:o:relaxed::😌💨🤲
:o:torelax::😌💨🎬
:o:joke::😂🔥❗
:o:toimagine::💭👀🎬
:o:throat::🧍🎵⚓
:o:anywhere::♾️❗⚓
:o:anyhow::👇⚡️
:o:whyever::♾️❗💡
:o:whichever::♾️❗
:o:whenever::♾️❗🕒
:o:wherever::♾️❗⚓
:o:however::2?
:o:however1::♾️❗🤲
:o:however2::👇⚡️
:o:whoever::♾️❗🧒
:o:whatever::♾️❗
:o:ufo::🛸
:o:anchor::⚓👌
:o:guardian::2?
:o:guardian1::🛡️🎬🧒
:o:guardian2::👀🛡️🎬🧒
:o:toguard::2?
:o:toguard1::🛡️🎬
:o:toguard2::👀🛡️🎬
:o:guard::👀🛡️🎬🧒
:o:stage::🎭⚓
:o:pedestal::⬆️⚓
:o:theater::2?
:o:theater1::🎭🏠
:o:theater2::🎭⭐
:o:running::🏃💨
:o:icon::😃👌〰️
:o:culture::🧒〰️🌍⭐
:o:milkglass::🥛
:o:driver::🚗🧒
:o:rider::🐴🧒
:o:smart::2?
:o:smart1::🧠🤲
:o:smart2::✨⭐🤲
:o:fullscore::💯
:o:hotbath::♨️
:o:handshake::🤝👌
:o:set::2?
:o:set1::🍽️👌
:o:set2::👥⭐
:o:furious::😠💢
:o:colorless::🎨⭐➖
:o:checkmark::✔️👌
:o:pope::⛪🤴🏻
:o:cowardly::🦁⚡️🤲
:o:coward::🦁⚡️🧒
:o:font::🔤👤⭐
:o:intuitive::❤️⭐🤲
:o:intuition::❤️⭐🔨💡🎬
:o:immediate::👇🕒🤲
:o:iconic::"😃🔨💬"
:o:beers::🍻
:o:tv::📺
:o:minidisk::💽
:o:disk::💿
:o:toupload::⬆️💾🎬
:o:upload::⬆️💾🎬
:o:todownload::⬇️💾🎬
:o:download::⬇️💾🎬
:o:floppydisk::💾
:o:cliche::♾️⚪=💭
:o:stereotyp::♾️⚪=💭
:o:nostril::👃🕳
:o:earhole::👂🕳
:o:asshole::🧍🍑⭐🕳
:o:ass::🧍🍑⭐
:o:citizen::🌍💦🏳️🧒
:o:defendant::⚖️⭐📖🛡️🎬🧒
:o:plaintiff::⚖️⭐📖⚔️🎬🧒
:o:sue::⚖️⭐📖⚔️🎬
:o:reward::2?
:o:reward1::🥈🎬
:o:reward2::🥈⭐
:o:issue::💭❗
:o:problematic::😟
:o:troublesome::😟
:o:awful::👎👎
:o:excellent::👍👍
:o:splendid::✨⭐🤲
:o:gratitude::🙏🙏
:o:polygarchie::👥📦🤴🏻👥
:o:dictatorship::1🧒📦🤴🏻👥
:o:monarch::🤴🏻
:o:monarchy::🤴🏻⭐
:o:democracy::♾️👥📦🤴🏻
:o:system::🎬🔨⭐
:o:oblique::❌👌🤲
:o:flame::🔥👌
:o:luxurious::✨⭐🤲
:o:luxury::✨⭐
:o:priest::⛪🤴🏻
:o:knight::🐴⚔️🧒
:o:armor::🛡️👚⭐
:o:warrior::⚔️🧒
:o:mansion::✨⭐🏠
:o:palace::✨⭐🏰
:o:umai::🍖🤲
:o:umami::🍖🤲
:o:spicy::🌶️🤲
:o:sour::🌻🎨🍋🤲
:o:salty::🧂🤲
:o:dull::2?
:o:dull1::👎🔪🤲
:o:dull2::😒
:o:message::💡🔥🎬❗
:o:messenger::💡🔥🎬🧒
:o:prophet::🙏⭐👆⛲🧒
:o:interesting::💡💖🎬
:o:boring::😒
:o:tointerest::💡💖🎬
:o:interest::👜💖🎬❗
:o:advantage::👍❗
:o:disadvantage::👎❗
:o:failure:🙃⭐
:o:dumpling::🥟
:o:dango::🍡
:o:well::3?
:o:well1::👍🤲
:o:well2::💧🕳
:o:well3::🤔
:o:privacy::🧒💭🤫
:o:security::⚠️⭐⚡️
:o:toreveal::🌟🔥🎬
:o:helpful::🎁💪🎬
:o:hopeful::💖🔍💭🎬
:o:resist::✊️🎬
:o:resistance::✊️⭐
:o:toaffect::🔀🔥🎬
:o:toinfluence::🔀🔥🎬
:o:influence::🔀🔥🎬
:o:preference::⚖️👍📦💭🎬
:o:toprefer::⚖️👍📦💭🎬
:o:tofavor::⚖️👍📦💭🎬
:o:tofavour::⚖️👍📦💭🎬
:o:favor::🎁🎬
:o:favour::🎁🎬
:o:bold::2?
:o:bold1::🦁🤲
:o:bold2::🐋🤲
:o:villain::👎🦁🧒
:o:hero::👍🦁🧒
:o:intention::🏁🎬
:o:tointend::🏁🎬
:o:tobelieve::✔️🤲📦💭🎬
:o:belief::✔️🤲📦💭
:o:faith::❤️🔨💡🎬
:o:finite::⛔♾️👌⭐🤲
:o:infinite::♾️👌⭐🤲
:o:toglisten::✨👌🎬
:o:toglitter::✨👌🎬
:o:risk::⚠️⭐
:o:zeal::🔥🧒💭
:o:horizon::☀️↗️⚓
:o:topractice::💡✨👣🎬
:o:lemon::🌻🎨🍋
:o:turban::👳💦👒
:o:compromise::🤝⭐😐
:o:worker::👷⭐
:o:torespect::2?
:o:torespect1::👍📦💭🎬
:o:torespect2::👍📦🌟🔥🎬
:o:veil::🧒👌🎁📝
:o:master::2?
:o:master1::♾️⚖️💡⭐🧒
:o:master2::🤴🏻🎬🧒
:o:custom::♾⚪🧒☝️🎬❗
:o:tax::🤴🏻👥🎁💰
:o:government::🤴🏻👥
:o:togovern::🤴🏻🎬
:o:toscare::😨🔥🎬
:o:scary::😨🔥🎬
:o:torelease::🚶💨👍🔥🎬
:o:sincere::🧍❤️⛲
:o:flattery::🍯💬
:o:toflatter::🍯💬🎬
:o:imitation::=🤲🔥📦❗
:o:toimitate::=🤲🔥📦
:o:broken::💥📬🎬🤲
:o:animal::🐒〰️
:o:invention::💭➕🧱🎬
:o:moss::🧱⬆️🚶🎬🌿
:o:vine::🧵🌼〰️
:o:ivy::🧱⬆️🚶🎬🌼〰️
:o:tocriticize::👎💬🎬
:o:tocritique::👎💬🎬
:o:critique::👎💦🔍💬
:o:criticism::👎💦🔍💬
:o:curtain::🏠💦👁️📝
:o:cinema::2?
:o:cinema1::🎦
:o:cinema2::🎦⚓
:o:fan::2?
:o:fan1::💨🎬⚙️⭐
:o:fan2::💨🎬🔨〰️
:o:feather::🐦🧍💪💦
:o:toreign::🤴🏻🎬
:o:reign::2?
:o:reign1::🤴🏻🎬
:o:reign2::🤴🏻🎬⚓
:o:slave::⛓️🎬🤲🧒
:o:collar::🧒👌⬇️💍
:o:heaven::👼⚓
:o:hell::👿⚓
:o:loud::🐘🤲🔊🤲
:o:deaf::👂⛔💪🎬
:o:blind::👀⛔💪🎬
:o:scythe::🌾🎁🐘🤲🔪
:o:toreap::🌾🔍🔪🎬
:o:tosow::🌾🔍↗️🎬
:o:grain::3?
:o:grain1::🌾
:o:grain2::🌾⛲🧂⭐
:o:grain3::🌳🧱⭐〰️👌
:o:crop::🌾
:o:torefuse::🙅🎬
:o:toerr::🙅🤲💭🎬
:o:error::🙅🤲💭
:o:wrong::🙅🤲
:o:toadvice::🎁💬🎬
:o:advice::🎁💬
:o:tocounsel1::🎁💬🎬
:o:counsel::🎁💬
:o:lost::🚶⚓🔍⛔💡🎬
:o:towander::🏁➖🚶🎬
:o:proverb::❗❗🕒💬
:o:nod::🧒👌⬆️⬇️🎬
:o:shakehead::🧒👌⬅️➡🎬
:o:toshakehead::🧒👌⬅️➡🎬
:o:contradiction::⚡️⭐
:o:constructionworker::👷
:o:construction::👷⭐
:o:hammerpick::⚒️
:o:hammerwrench::🛠️
:o:sight::❓👀🎬
:o:toforge::⚔️〰️🧱🎬
:o:forge::⚔️〰️🧱🎬⚓
:o:smith::⚔️〰️🧱🎬🧒
:o:amboss::⚔️〰️🧱🎬📝🤲❗
:o:haze::🌫️
:o:toremain::⚓🎬
:o:aroma::👃➕💭
:o:scent::👃➕💭
:o:structured::📏🎬🤲
:o:poem::📏⭐💬
:o:toperceive::👀〰️
:o:perception::👀〰️
:o:sense::2?
:o:sense1::👀〰️
:o:sense2::❤️⭐
:o:outline::👤⭐
:o:injured::🤕🤲
:o:injury::🤕⭐
:o:wound::🧍🤕
:o:viscous::🐢🤲💧🤲
:o:glue::🩹🤲💧
:o:toglue::🩹🤲💧🎬
:o:sticky::🩹🤲
:o:fluid::2?
:o:fluid1::💧⭐
:o:fluid2::💧🤲
:o:urine::🌻🎨💧
:o:piss::🌻🎨💧
:o:sperm::🍆⭐🐄🥛
:o:futile::⛔🔥⭐🤲
:o:chunk::🥌〰️
:o:curlingstone::🥌
:o:sauna::🧖⭐
:o:solid::🧱🤲
:o:desperate::😫
:o:comrade::👥🧒
:o:todrown::💧💡☠️🎬
:o:togiveup::😫💡⛔👣🎬
:o:distraught::😫
:o:weary::😩
:o:fate::🔮⭐
:o:destiny::🔮⭐
:o:todetermine::💡🤲🔥🎬
:o:totoil::💪👌🎬
:o:invain::⛔🔥⭐🤲
:o:toslide::2?
:o:toslide1::🎿🎬
:o:toslide2::🎿🔥🎬
:o:slide::🎿❗
:o:butter::🧈
:o:rugged::🧈⚡️🤲
:o:smooth::🧈🤲
:o:surface::📝🤲❗
:o:thirsty::🍹⭐💖🤲
:o:thirst::🍹⭐💖
:o:farmer::🍽️⭐🎁🌾🏠🧒
:o:virtue::👍⭐
:o:goodness::👍⭐
:o:pot::🏺〰️
:o:bench::🧵🤲🪑
:o:economy::💰🔨🔄✋️🎁🎬
:o:totrade::🔄✋️🎁🎬
:o:toexchange::🔄✋️🎁🎬
:o:mutual::🔄🤲
:o:bookmark::🔖
:o:toblossom::🌼🎬
:o:tomb::☠⚓
:o:tome::🐘🤲📖
:o:toadjust::🎚️🎬
:o:slider::🎚️
:o:inlove::😍
:o:hearteyes::😍
:o:airkiss::😘
:o:tospill::🍷💦👌🎬
:o:tothrow::🏀🎬
:o:clapperboard::🎬👌
:o:volleyball::🏐
:o:fishingrod::🎣
:o:fishing::🎣⭐
:o:bowling::🎳
:o:basketball::🏀
:o:baseball::⚾
:o:dynasty::🤴🏻👪🕒
:o:included::⏺️⚓📦🤲
:o:include::⏺️⚓📦
:o:diagram::📊〰️
:o:function::2?
:o:tofunction::👍⭐🎬
:o:function1::💪🎬❗
:o:function2::📈🔢
:o:graph::📈
:o:data::📊⭐
:o:hippo::🦛
:o:hippopotamus::🦛
:o:witcher::🧙‍⭐🎬🧒
:o:jug::🧴⭐
:o:topack::📦🎬
:o:boxing::🥊
:o:tojudge1::⚖️⭐🎬
:o:judge::⚖️⭐🎬🧒
:o:shiro::🏯
:o:alchemy::⚗️⭐
:o:tovow::🙋💬🎬
:o:vow::🙋💬🎬
:o:solemn::😐
:o:serious::⛔😃
:o:mineral::💎〰️
:o:sphinx::🐫⚓🔺🦁🧒
:o:pyramid::🐫⚓🔺
:o:rectangle::🔲〰️
:o:pangram::♾️🔤👜📝
:o:biscuit::🍪
:o:bonbon::🍬
:o:sweets::🍭⭐
:o:weapon::⚔️〰️
:o:halloween::🎃🕒
:o:lettuce::🥬
:o:sushi::🍣
:o:peanut::🥜
:o:peanuts::🥜
:o:tostitch::📌🧵🎬
:o:stitch::📌🧵
:o:inn::🤏🕒💰🔨🏠🎬⚓
:o:vocabulary::💬💦📝
:o:recording::🎤‍🎬❗
:o:podcast::🔄🕒🎤‍🎬❗
:o:regular::🔄🕒
:o:audiobook::👂📖
:o:video::👀❗
:o:audio::👂❗
:o:heartbreak::💔
:o:toleak::💦👌🎬
:o:leak::💦👌⚓
:o:tosnore::💤🔊🎬
:o:todrool::💤👄💦👌🎬
:o:tospit1::👄💦👌🎬
:o:spit::👄💦👌
:o:sweat::🧒💦👌
:o:throne::🤴🏻🪑
:o:coala::🐨
:o:ox::🐂
:o:camel::2?
:o:camel1::🐪
:o:camel2::🐫
:o:hare::🐇
:o:comet::🌟☄️
:o:tire::🚗🎡⭐
:o:rubber::🛀🦆🧱⭐
:o:rubberduck::🛀🦆
:o:flamingo::🦩
:o:octopus::🐙
:o:shark::🦷🦈
:o:cricket::🦗
:o:pork::🐷🍖
:o:beef::🐄🍖
:o:poultry::🐦🍖
:o:meatleg::🍗
:o:suv::🚙
:o:toreplace::🔀🎬
:o:replacement::🔀🎬❗
:o:tosubstitute::🔀🎬
:o:substitute::🔀🎬❗
:o:missive::✉️📝
:o:dumb::🧠⚡️🤲
:o:toduel::🤺🎬
:o:duel::🤺⭐
:o:darkness::🌙🕒🤲⭐
:o:kebab::🥙
:o:gyros::🥙
:o:gyro::🥙
:o:doughnut::🍩
:o:donut::🍩
:o:cookie::🍪
:o:core::🍎〰️💦🥜
:o:seed::🍎〰️💦🥜
:o:popcorn::🍿
:o:taco::🌮
:o:bagel::🥯
:o:scene::🎦💦
:o:barberpole::💈
:o:ambiguous::2💭🔥🎬
:o:ambiguity::2💭🔥🎬❗
:o:exaggeration::🤯🐘🤲💬
:o:toexaggerate::🤯🐘🤲💬🎬
:o:mist::🌫️
:o:myth::👴🤲💬💬
:o:empire::🐘🤲🤴🏻🏳️⚓
:o:emperor::🐘🤲🤴🏻
:o:solarsystem::☀️💫
:o:galaxy::🌟🌀
:o:spiral::🌀
:o:firmament::🌟⚓
:o:avatar::💻⭐🕸️
:o:alias::🔀❓📣
:o:internet::💻⭐🕸️
:o:pottery::2?
:o:pottery1::🏺🧱⭐
:o:pottery2::🏺🧱🎬
:o:handmike::🎤
:o:handmicrophone::🎤
:o:song::🎵🎤
:o:avenger::⚖️⭐🎁💢🧒
:o:vengeance::⚖️⭐🎁💢
:o:torevenge::⚖️⭐🎁💢🎬
:o:toavenge::⚖️⭐🎁💢🎬
:o:justice::⚖️⭐
:o:transform::✨
:o:titan::🐘🐘🤲🧒
:o:field::🌿⚓
:o:matrix::🔢👌
:o:missing::⛔📦🤲
:o:never::⛔❗🕒
:o:danger::⚠️⭐
:o:wing::🐦🧍💪
:o:beveragebox::🧃
:o:mate::🧉
:o:straw::2?
:o:straw1::🥤⬆️💦
:o:straw2::☠️🤲🌾
:o:toheal::👍🔥🎬
:o:suit::🐧🤲👚⭐
:o:hatch::🐣🎬
:o:turkey::🦃
:o:peacock::🦚
:o:penguin::🐧
:o:swan::🦢
:o:owl::🦉
:o:adult::🧍🤲🧒
:o:fighter::⚔️🧒
:o:maker::🧱🎬🧒
:o:beauty::2?
:o:beauty1::👀👍⭐
:o:beauty2::👀👍🧒
:o:saw::🦷🔪
:o:craft::📏🔨⭐
:o:artisan::📏🔨⭐🧒
:o:tosplit::💦✨🔪🎬
:o:analyst::💦🔍💡🎬🧒
:o:toanalyze::💦🔍💡🎬
:o:analysis::💦🔍💡🎬❗
:o:discovery::1.🕒💡✨🎬❗
:o:golden::2?
:o:golden1::👑🧱⭐🤲
:o:golden2::Au🤲
:o:flow::🌊🎬
:o:wolf::🐺
:o:donkey::🐘🤲👂👜🐴
:o:dishwasher::2?
:o:dishwasher1::🍽️🔍💧🧽🎬⚙️⭐
:o:dishwasher2::🍽️🔍💧🧽🎬🧒
:o:timespan::⌛⭐
:o:awhile::🤏🕒
:o:windmill::🌾🎁💨🏠
:o:mill::🧂⭐🧱🎬⚙️⭐
:o:powder::🧂⭐
:o:valuable::👍⭐👜
:o:value::👍⭐🔢
:o:daring::🦁🤲
:o:sage::🧙🏻🤲🧒
:o:toweave::👚⭐🔗🎬
:o:spindle::🧵📏
:o:hanger::👚⭐📏
:o:loom::🧵🎬⚙️⭐
:o:festival::🎉🕒
:o:cancer::🦀🤒🌡️
:o:illness::🤒🌡️
:o:crab::🦀
:o:wonderful::✨⭐
:o:todare::🦁🎬
:o:weed::🌿
:o:various::🔀🔀
:o:colorful::🎨⭐🤲
:o:kid::🌳🤲↗️🎬🧒
:o:cucumber::🥒
:o:banjo::🪕
:o:shamisen::⛩🪕
:o:trumpet::🎺
:o:saxophone::🎷
:o:guitar::🎸
:o:togrip::✊️👌🎬
:o:grip::👜👌⬆️💦
:o:hairbrush::🧒👌🌿🎁🧹
:o:tobrush::🧹🎬
:o:brush::🖌️〰️
:o:sweep::🧹🎬
:o:incorrect::✔️⚡️🤲
:o:decent::☝️🤲
:o:material::🧱⭐
:o:velvet::🧸✋️🎬🤲🧱⭐
:o:detective::🕵🏻
:o:crimson::❤️🎨
:o:violence::👊⭐
:o:violent::👊⭐🤲
:o:saint::🙏⭐🧒
:o:angel::👼
:o:angle::📐⭐
:o:parallel::=👌🤲
:o:chain::⛓️
:o:potent::💪⭐🤲
:o:potency::💪⭐🤲⭐
:o:belly::🧍⏺️👜👌
:o:bellybutton::🧍💦🔘
:o:button::2?
:o:button1::👚⭐🔘
:o:button2::💻〰️🔘
:o:yearly::♾️🌼➡️❄️🕒
:o:monthly::♾️🌙⌛
:o:daily::♾️☀️🕒
:o:self::↩️🧍
:o:meaning::💭🔥🎬❗
:o:worth::👍⭐
:o:worthy::👍🙂🤲
:o:sociology::👥⭐⚗️⭐
:o:linguistics::💬🔨⭐⚗️⭐
:o:physics::❗💭⚗️⭐
:o:computerscience::💻⭐⚗️⭐
:o:mathematics::🔢⚗️⭐
:o:knowledge::💡⭐
:o:wisdom::🧙🏻🤲⭐
:o:philosophy::🧙🏻🤲⭐❤️
:o:philosopher::🧙🏻🤲⭐❤️🧒
:o:milkyway::🌟🌟🚶⚓
:o:nightsky::🌙🕒☁️⚓
:o:compass::🧭
:o:misses::✨⭐👩
:o:mister::✨⭐👨
:o:mr::✨⭐👨
:o:wall::🚧〰️
:o:international::🌍🏳️🏳️🤲
:o:symbol::🔤〰️
:o:emoji::😃👌〰️
:o:hey::👋💬
:o:paragraph::📝💦
:o:text::📝
:o:language::2?
:o:language1::💬🔨⭐
:o:language2::💬
:o:pond::💧🕳
:o:lightray::☀️⛲🔱
:o:article::💬💦
:o:declaration::💡🔥🎬❗
:o:todeclare::💡🔥🎬
:o:topraise::👍💬🎬
:o:dignity::👍⭐👜
:o:worth::👍⭐
:o:conscience::👍✖️👎💡🎬
:o:cycle::🔄🕒
:o:season::🌼♨️🍂❄️🕒
:o:toreverse::↩️🎬
:o:reverse::↩️🤲
:o:reflexive::↩️🤲
:o:toshower::🚿🎬
:o:shower::🚿
:o:bathtub::🛁
:o:tub::🛁⭐
:o:final::♾️⚖️➡🤲
:o:finally::♾⚖️➡🤲
:o:cave::⛰️🕳
:o:valley::⛰⬇️💦🚶⚓
:o:eggshell::🥚🐚⭐
:o:phoenix::🔥🐦
:o:jungle::🦁🌳🌳
:o:pearl::🦪⚽〰️
:o:oyster::🦪
:o:tohunt::🏹🎬
:o:whole::♾️🤲
:o:january::1/12🌙⌛
:o:february::2/12🌙⌛
:o:march::3/12🌙⌛
:o:april::4/12🌙⌛
:o:may::5/12🌙⌛
:o:june::6/12🌙⌛
:o:july::7/12🌙⌛
:o:august::8/12🌙⌛
:o:september::9/12🌙⌛
:o:october::10/12🌙⌛
:o:november::11/12🌙⌛
:o:december::12/12🌙⌛
:o:monday::1/7☀️🕒
:o:tuesday::2/7☀️🕒
:o:wednesday::3/7☀️🕒
:o:thursday::4/7☀️🕒
:o:friday::5/7☀️🕒
:o:saturday::6/7☀️🕒
:o:sunday::7/7☀️🕒
:o:saturn::🪐
:o:plaza::🏘️🔲⚓
:o:minor::🐭🤲
:o:major::🐘🤲
:o:grand::🐘🤲
:o:challenge::⚔️➡👍✖️👎
:o:toconjecture::🤔🎬
:o:toguess::🤔🎬
:o:toboom::🌳🤲↗️🎬
:o:toflourish::🌼🎬
:o:mrs::✨⭐👩
:o:quality::👍⭐
:o:everything::♾️❗
:o:greetings::👋💬💬
:o:pumpkin::🎃
:o:sir::✨⭐👨
:o:madam::✨⭐👩
:o:mam::✨⭐👩
:o:bye::👋💬➕🚶💨
:o:byebye::👋💬➕🚶💨
:o:todepart::🚶💨🎬
:o:goodmorning::👋💬☀️
:o:goodevening::👋💬☀️↘️🕒
:o:goodday::👋💬
:o:fairytale::🧚💬
:o:fairy::🧚
:o:ingredient::🧱⭐
:o:secret::2?
:o:secret1::🤫🤲
:o:secret2::🤫❗
:o:episode::💬💬💦
:o:birthmark::🧍💦❌👌〰️
:o:cute::🐤❤️🤲
:o:yellow::🌻🎨
:o:violet::🍇🎨
:o:tocollide::💥🎬
:o:collision::💥
:o:potion::🧙‍⭐🍹⭐
:o:cage::🚶💨⛔💪🎬⚓
:o:tofuck::🧍🍆⭐🎬
:o:fuck::🖕
:o:middlefinger::🖕
:o:livestock::🐷〰️
:o:wool::🐏🌯⭐
:o:watercolor::💧🎨
:o:zombie::🧟
:o:infinity::♾️👌⭐
:o:pronoun::👆
:o:pro::👆
:o:toshovel::🕳⛏️🎬
:o:shovel::🕳🔨〰️
:o:todig::🕳⛏️🎬
:o:tosuffer::😥⭐🎬
:o:suffering::😥⭐
:o:information::💡🎬❗
:o:todefend::🛡️🎬
:o:defense::🛡️⭐
:o:intelligent::🧠🤲
:o:intelligence::🧠🤲⭐
:o:curious::2?
:o:curious1::💡💖🎬
:o:curious2::❓⭐🤲
:o:curiosity::💡💖🎬
:o:mystery::❓⭐
:o:mysterious::❓⭐🤲
:o:nail::2?
:o:nail1::🔨👌📌
:o:nail2::☝️👌📌
:o:tip::⬆️💦
:o:bug::🐞〰️
:o:ladybug::🐞
:o:worm::〰️👌🐞
:o:compassionate::🥺🔍❤️⭐🎬
:o:hail::👋
:o:sinner::🙏⭐⚡️🧒
:o:tosin::🙏⭐⚡️🎬
:o:sin::🙏⭐⚡️❗
:o:criminal::⚖️⭐📖⚡️🧒
:o:crime::⚖️⭐📖⚡️
:o:blessing::2?
:o:blessing1::💬🔨👍🔥
:o:blessing2::👍🎁
:o:tobless::2?
:o:tobless::💬🔨👍🔥🎬
:o:tobless::👍🎁
:o:feeling::2?
:o:feeling1::❤️⭐
:o:feeling2::✋️⭐
:o:pity::2?
:o:pity1::🥺🔍❤️⭐🎬
:o:pity2::🥺🔍❤️⭐
:o:sympathy::🥺🔍❤️⭐
:o:compassion::🥺🔍❤️⭐
:o:mercy::🥺🔍❤️⭐
:o:merciful::🥺🔍❤️⭐🎬
:o:grace::2?
:o:grace1::✨⭐
:o:grace2::🥺🔍❤️⭐
:o:graceful::2?
:o:graceful1::✨⭐🤲
:o:graceful2::🥺🔍❤️⭐🎬
:o:gracious::2?
:o:gracious::✨⭐🤲
:o:gracious::🥺🔍❤️⭐🎬
:o:grateful::🙏🙏🤲
:o:apologetic::🙇🤲
:o:totempt::👎💖🔥🎬
:o:temptation::👎💖❗
:o:debt::✋️🎁⚠️🎬❗
:o:debitor::✋️🎁⚠️🎬🧒
:o:kingdom::🤴🏻🏳️⚓
:o:holy::🙏⭐
:o:fist::✊️👌
:o:movie::🎬👌⭐
:o:hands::🤲👌
:o:scales::⚖️👌
:o:drops::💦👌
:o:brick::1🧱👌
:o:bricks::🧱👌
:o:postbox::📬👌
:o:mailbox::📬👌
:o:tosparkle::✨👌🎬
:o:sparkle::✨👌
:o:loupe::🔍👌
:o:magnifyingglass::🔍👌
:o:magnifier::🔍👌
:o:tomagnify::🔍👌🎬
:o:cause::💡⭐
:o:lightning::⚡️👌
:o:thunder::⚡️👌
:o:lightningbolt::⚡️👌
:o:+::➕
:o:plus::➕🔢
:o:-::➖
:o:minus::➖🔢
:o:x::✖️
:o:times::✖️🔢
:o:division::➗🔢
:o:todivide::➗🎬
:o:divided::➗🎬🤲
:o:palm::🌴👌
:o:palmtree::🌴👌
:o:okay::👍⚪
:o:topray::🙏👌🎬
:o:deliberate::2?
:o:deliberate1::💭🎬
:o:deliberate2::🏁🤲
:o:toponder::💭💭🎬
:o:artwork::🎨🖼️〰️
:o:agreement::🤝⭐
:o:alcohol::🍶〰️
:o:alot::❗❗
:o:among::⏺️⚓
:o:brothers::👪➕👦👦
:o:beginning::⛲📦
:o:beverage::🍹〰️
:o:planet::🌍〰️
:o:universe::♾️🌟
:o:wallet::💰👜👌
:o:metal::⚓👌🧱⭐
:o:civilization::🧒〰️🌍⭐
:o:carrot::🥕
:o:those::👆👆
:o:ribbon::🎀
:o:bouquet::💐
:o:attempt::👀⭐
:o:phone::☎️
:o:tolick::👅🎬
:o:tongue::👅
:o:seal::2?
:o:seal1::✉️📝🔍🔐
:o:seal2::🌊⚓🐶
:o:hedgehog::🦔
:o:rose::🌹
:o:spike::🔪🤲❗
:o:thorn::🌼〰️💦🔪
:o:sign::2?
:o:sign1::💡🔥🎬❗
:o:sign2::🛑👌〰️
:o:tosign::📣❗🔍✍️🎬
:o:magic::🧙‍⭐
:o:watery::💧🤲
:o:socks::🧦
:o:toroll::🎡🎬
:o:toascend::⬆️🚶🎬
:o:complicated::💡😧🎬
:o:mechanical::⚙️🤲
:o:silent::🤐
:o:elbow::💪🔗⚓
:o:hourglass::⌛
:o:crayon::🖍️
:o:desert::🐫⚓
:o:sailingship::💨🔨🚢
:o:toexamen::🔍👌🔨👀🎬
:o:examen::🔍👌🔨👀🎬
:o:wounded::🤕🤲
:o:velocity::🏃💨🤲⭐
:o:stealth::🤫🤲
:o:stealthy::🤫🤲
:o:memory::🧒👌⏺️⚓📝
:o:fictitious::💭🤲
:o:unreal::⛔🌍💦🤲
:o:lawful::⚖️⭐📖🤲
:o:legal::⚖️⭐📖🤲
:o:microphone::🎙️
:o:radiowave::📡🔊
:o:royal::👑🤲
:o:punishment::🥈⚡️
:o:plug::2?
:o:plug1::🔌
:o:plug2::📏〰️
:o:rope::🚢🎁🧵
:o:togather::2?
:o:togather1::📚〰️🎬
:o:togather2::👥✨🎬
:o:toprepare::💪🔥🎬
:o:product::🧱🎬❗
:o:probable::🤔🤲
:o:penalty::🥈⚡️
:o:arrow::➡️👌
:o:property::👜❗
:o:status::❓🤲⭐
:o:society::2?
:o:society1::🔐👥
:o:society2::👥⭐
:o:rod::📏〰️
:o:stick::2?
:o:stick1::📏〰️
:o:stick2::🩹🎬
:o:toothbrush::🦷🎁📏〰️
:o:alien::👾
:o:airplane::✈️
:o:smoke::🚬💨
:o:gas::2?
:o:gas1::🚬💨
:o:gas2::⛽💧
:o:pen::✒️
:o:fountain::⛲👌
:o:toselect::✖️🎬
:o:suddenly::😮🕒🤲
:o:tooccur::📦🎬
:o:occasion::❗🎬🕒
:o:event::❗🎬🕒
:o:painful::🤕❤⭐🔥🎬
:o:otherwise::⛔👇➡⭐
:o:ordered::🔢👜
:o:ordering::🔢👜🔨⭐
:o:kiwi::🥝
:o:contrary::⚡️🤲
:o:contrast::⚡️⭐
:o:counterpart::⚡️❗
:o:barrel::🛢️
:o:oillamp::🪔
:o:previous::⬅️🤲
:o:tofollow::🚶🚶🎬
:o:vicinity::👇⚪⚓🤲⭐
:o:line::〰️👌
:o:experimentation::👀⭐🎬
:o:experiment::👀⭐🎬❗
:o:toexperiment::👀⭐🎬
:o:image::🖼️
:o:remainder::➖🎬➡❓
:o:sum::➕🔢🔥⭐
:o:balanced::⚖️👌🤲
:o:robot::⚙️⭐🧒
:o:printer::🖨️
:o:lucky::☘️🤲
:o:locked::🔒🤲
:o:daylight::☀️⛲❗
:o:lifetime::🧒⌛
:o:lifespan::🧒⌛
:o:envelope::✉️
:o:loveletter::💌
:o:recent::🤏⬅️🕒🤲
:o:lord::✨⭐👨
:o:nobility::✨⭐👥
:o:joint::🔗⚓
:o:category::📦⭐
:o:merge::1✨🎬
:o:personal::🧒👜
:o:melon::🍉⭐
:o:watermelon::🍉
:o:tomato::🍅
:o:grapes::🍇
:o:avocado::🥑
:o:liquid::2?
:o:liquid1::💧⭐
:o:liquid2::💧🤲
:o:strawberry::🍓
:o:cherry::🍒
:o:jam::🐢🤲💧
:o:jar::🏺〰️
:o:cow::🐄
:o:couple::💑
:o:marriage::💑💍
:o:married::💑💍🤲
:o:hunger::🍽️⭐💖
:o:guest::🤏🕒🏠🎬🧒
:o:host::🤏🕒🏠🔥🎬🧒
:o:ill::🤒🌡️🤲
:o:wrap::2?
:o:wrap1::🌯🎬
:o:wrap2::🌯
:o:heavyweight::🏋️
:o:weightlift::🏋️🎬
:o:lifting::🏋️
:o:countryside::🌳🌾⚓
:o:average::♾️🎁=🤲🔢
:o:expectation::🤔🤔
:o:todescribe::❗🤲💬🎬
:o:description::❗🤲💬
:o:commander::🔥🎬🧒
:o:commandment::🔥🎬❗
:o:revolver::🔫⭐
:o:pistol::🔫⭐
:o:rodent::🐀
:o:humanity::♾️🧒⭐
:o:human::🧒〰️
:o:leader::🚶🔥🎬🧒
:o:park::🌳⚓
:o:todisconnect::⛔🔗🔥🎬
:o:toconnect::🔗🔥🎬
:o:important::⚠️⚪🎬
:o:todisappear::💨🤲✨📦
:o:gone::💨🤲
:o:foolish::🧙🏻⚡️🤲
:o:parrot::🦜
:o:ceiling::🏠📦⭐👒
:o:loose::➰🤲
:o:knot::🎀〰️
:o:tobind::🔗🔥🎬
:o:secure::⚓👌🤲
:o:detail::🤏⭐
:o:detailed::🤏⭐🤲
:o:thread::🧵
:o:steak::🥩
:o:animalfarm::🍽️⭐🐷〰️⚓
:o:tolift::🏋️🎬
:o:center::2?
:o:center1::⏺️⚓
:o:center2::⏺️⚓🤲
:o:explanation::💡🔥🎬❗
:o:energy::🧍💪⭐🎁❗
:o:exception::⛔♾️🤲❗
:o:law::⚖️⭐📖
:o:lawyer::⚖️⭐📖🧒
:o:true::✔️🤲
:o:truth::✔️⭐
:o:veracity::✔️⭐
:o:false::⛔✔️🤲
:o:falsity::⛔✔️⭐
:o:toassert::✔️🤲📦🔍💬🎬
:o:assertion::✔️🤲📦🔍💬🎬❗
:o:toexamine::🔍🤲👀🎬
:o:required::⚠️🎬
:o:necessary::⚠️🎬
:o:necessity::⚠️🎬❗
:o:requirement::⚠️🎬❗
:o:eternal::♾️🕒🤲
:o:eternity::♾️🕒
:o:odd::2?
:o:odd1::➗2⛔💪🎬
:o:odd2::⛔♾️🤲
:o:peculiar::⛔♾️🤲
:o:peculiarity::⛔♾️🤲❗
:o:normal::♾️⚪🤲
:o:almost::⚪
:o:tosatisfy::😃🔥🎬
:o:satisfaction::😃🔥⭐
:o:satisfactory::😃🔥🎬
:o:satisfied::😃🤲
:o:void::🐚🤲
:o:husk::🐚⭐
:o:done::🎬🤲
:o:teacher::💡🔥🎬🧒
:o:university::🎓⚓
:o:tograduate::🎓🎬
:o:graduate::🎓📬🎬🧒
:o:graduation::🎓🎬
:o:earning::📨🎬💰
:o:towin::⚔️➡👍🎬
:o:win::⚔️➡👍
:o:togain::📨😃🎬
:o:gain::📨😃
:o:loss::3?
:o:loss1::⛔👜✨
:o:loss2::⛔👜✨❗
:o:loss3::⚔️➡️👎
:o:todefeat::⚔️➡️👎🔥🎬
:o:defeat::⚔️➡️👎
:o:earlier::⬅️🕒🤲
:o:later::➡️🕒🤲
:o:same::=
:o:identity::2?
:o:identity1::=⭐
:o:identity2::❓📦💡
:o:equality::=🤲⭐
:o:difference::🔀⭐
:o:vehicle::🚗〰️
:o:tostink::💩💨🎬
:o:dwarf::🐭🤲🧒
:o:giant::2?
:o:giant1::🐘🤲🧒
:o:giant2::🐘🐘🤲
:o:container::📦〰️
:o:tocontradict::⚡️🎬
:o:dependence::🔗⚠️🎬
:o:exist::📦
:o:agency::👥
:o:reason::💡⭐
:o:toreason::💡⭐🔨🎬
:o:topic::💭
:o:addition::➕🔢
:o:subtraction::➖🔢
:o:alternative::✖️
:o:option::✖️
:o:multiplication::✖️🔢
:o:division::➗🔢
:o:consequence::➡❓
:o:toquote::""🔨🎬
:o:quote::""💬
:o:tocommand::🔥🎬
:o:command::🔥🎬❗
:o:concrete::👌⭐
:o:abstract::⭐⭐
:o:torequest::🙏🎬
:o:possibility::🤔
:o:appearance::🌟
:o:ability::💪
:o:evil::👿⭐
:o:duty::⚠️🎬
:o:toattempt::👀⭐🎬
:o:halt::🛑
:o:anger::😠💢
:o:desire::💖
:o:dislike::💔
:o:distaste::💔
:o:aversion::💔
:o:repugnance::💔
:o:ease::🙂
:o:easiness::🙂
:o:hardship::😧
:o:difficulty::😧
:o:accident::🙃
:o:object::2?
:o:object1::🔍⭐
:o:object2::❗
:o:total::♾️🤲
:o:unique::🦄🤲
:o:agent::❗🎬🧒
:o:topunch::👊🎬
:o:tostab::🗡️🎬
:o:death::💀⭐
:o:cafe::☕⚓
:o:cafeteria::☕⚓
:o:loudspeaker::🔊👌
:o:device::☎️〰️
:o:gadget::☎️〰️
:o:toscream::2?
:o:toscream1::📣🎬
:o:toscream2::😱🎬
:o:christian::✝️
:o:choice::✖️🎬
:o:snowflake::❄️
:o:herb::🌿
:o:broccoli::🥦
:o:comfort::🙂🤲
:o:maize::🌽
:o:oneanother::➡⬅️
:o:edge::📏〰️👌
:o:straight::2?
:o:straight1::📏🤲
:o:straight2::📏⭐
:o:precise::🔍👌🤲
:o:logic::💡🔍🔨🎬
:o:globe::🌍
:o:exhale::👄⛲💨🎬
:o:inhale::👄📬💨🎬
:o:breath::👄💨
:o:drama::🎭
:o:howmany::❓🔢
:o:howlong::❓⌛
:o:least::♾️⚖️🤏
:o:exclamation::❗💬
:o:painting::🎨🖼️
:o:statue::🗿〰️
:o:palette::🎨👌
:o:painter::🎨🧒
:o:girl::👧
:o:child::👪🧒
:o:children::👪🧒🧒
:o:sisters::👪➕👧👧
:o:sibling::👪🧒➕🧒
:o:siblings::👪➕🧒🧒
:o:oldman::👴
:o:senior::👴
:o:junior::👪👦
:o:granpa::👪👴
:o:oldwoman::👵
:o:grandma::👪👵
:o:parents::👪👨👩
:o:grandparents::👪👴👵
:o:strength::🧍💪⭐
:o:ox::🐮
:o:seaspray::🌊💦👰🏻🎨
:o:surf::🌊💦👰🏻🎨
:o:tosurf::🏄🎬
:o:sea::🌊⚓
:o:ocean::🌊⚓
:o:lake::🤏🌊⚓
:o:river::🚶🎬🌊⚓
:o:tunnel::⛰️⏺️🚶⚓
:o:togreet::👋🎬
:o:greeting::👋🎬
:o:tokiss::💋🎬
:o:kiss::💋🎬
:o:wood::🌳🧱⭐
:o:wooden::🌳🧱⭐🤲
:o:document::📝
:o:salad::🥗
:o:ricebowl::🍚
:o:onigiri::🍙
:o:onsen::♨️💧⚓
:o:hotbath::♨️💧⚓
:o:osake::🍶
:o:champagne::🍾
:o:pregnant::🤰🤲
:o:pregnancy::🤰
:o:dizzystars::💫
:o:croissant::🥐
:o:bacon::🍳🥓
:o:dawn::☀️↗️🕒
:o:dusk::☀️↘️🕒
:o:noon::☀️⬆️🕒
:o:midday::☀♾️⚖️⬆️🕒
:o:direct::✋️🎬🤲
:o:topinch::🥢🎬
:o:toslap::✋️💥🎬
:o:lunch::☀⬆️🕒🍽️⭐
:o:eat::🍽️⭐🎬
:o:dinner::☀️↘️🕒🍽️⭐
:o:sunsea::🌅
:o:building::🏠〰️
:o:penis::🧍🍆⭐
:o:vagina::👩🕳
:o:wifi::📶
:o:tea::🍃☕
:o:strawcup::🥤
:o:visible::👀💪🎬
:o:electro::⚡️⭐
:o:electronic::⚡️⭐
:o:electricity::⚡️⭐
:o:device::☎️〰️
:o:tocompare::⚖️🎬
:o:heat::♨️🤲⭐
:o:toheat::♨️🎬
:o:temperature::♨️📏
:o:top::2?
:o:top1::⬆️⚓
:o:top2::⬆️💦
:o:spirit::2?
:o:spirit1::🧒💭
:o:spirit2::👻
:o:courage::🦁🤲⭐
:o:sloth::🦥
:o:thunderstorm::⛈
:o:year::🌼➡️❄️🕒
:o:dino::🦕
:o:beckon::👋
:o:biceps::💪👌
:o:towarn::⚠️⭐🔍💬🎬
:o:warning::⚠️⭐🔍💬
:o:tobeware::⚠️⭐🔍👀🎬
:o:undesired::💔
:o:anguish::😧
:o:horn::2?
:o:horn1::1🤘
:o:horn2::📯
:o:horns::🤘
:o:crossed::🤞
:o:victory::2?
:o:victory1::⚔️➡️👍
:o:victory2::✌️
:o:toclap::👏🎬
:o:tocelebrate::🙌🎬
:o:celebration::🙌
:o:joy::😃
:o:discontent::🙁
:o:frown::☹️
:o:wink::😉
:o:unimpressed::😑
:o:annoyed::😒
:o:boring::😒
:o:bored::😒
:o:neutral::😐
:o:sleepy::😴
:o:disbelief::😦
:o:surprise::😯
:o:flushed::😳
:o:astonished::😲
:o:dizzy::😵
:o:persevere::😣
:o:shame::😞
:o:scared::😨
:o:frightened::😨
:o:anxious::😨
:o:nervous::😨
:o:sneeze::🤧
:o:nauseous::🤢
:o:vomit::🤮
:o:freezing::🥶
:o:partying::🥳
:o:smirk::😏
:o:blush::😊
:o:angryface::😠
:o:steamface::😤
:o:devil::👿
:o:flustered::😅
:o:relief::😌
:o:laugh::😂
:o:rofl::🤣
:o:tired::🥱
:o:mask::2?
:o:mask1::😷
:o:mask2::🎭
:o:sneeze::🤧
:o:sunglassesface::😎
:o:spicyface::🥵
:o:hotface::🥵
:o:sad::😥
:o:mute::🤐
:o:terror::😱
:o:ohmy::🤭
:o:mhm::🤔
:o:tasty::😋
:o:amazed::🤩
:o:amazing::🤩
:o:goofy::🤪
:o:shush::🤫
:o:hush::🤫
:o:eyeroll::🙄
:o:plead::🥺
:o:crying::😭
:o:mosquito::🦟
:o:bat::🦇
:o:ant::🐜
:o:reptile::🦎
:o:shell::2?
:o:shell1::🐚
:o:shell2::🐚⭐
:o:snake::🐍
:o:clownfish::🐠
:o:rat::🐭
:o:mouse::2?
:o:mouse1::🐭
:o:mouse2::🖱️
:o:eagle::🦅
:o:whale::🐋
:o:trex::🦖
:o:snail::🐌
:o:slug::🐌
:o:tiger::🐯
:o:ewe::🐑
:o:zebra::🦓
:o:rhino::🦏
:o:rhinoceros::🦏
:o:turtle::🐢
:o:rabbitface::🐰
:o:rooster::🐓
:o:unicorn::🦄
:o:butterfly::🦋
:o:dragon::🐉
:o:frog::🐸
:o:kangaroo::🦘
:o:spider::🕷️
:o:scorpion::🦂
:o:web::🕸️
:o:caterpillar::🐛
:o:bacterium::🦠
:o:dove::🕊️👌
:o:pigeon::🕊️👌
:o:lobster::🦞
:o:shrimp::🦐
:o:squid::🦑
:o:dolphin::🐬
:o:rabbit::🐇
:o:hamster::🐹
:o:monkeyface::🐵
:o:nosee::🙈
:o:nohear::🙉
:o:nospeak::🙊
:o:nosay::🙊
:o:chipmunk::🐿️
:o:squirrel::🐿️
:o:wheat::🌾
:o:eggplant::🍆
:o:tulip::🌷
:o:conifer::🌲
:o:christmas::🎄🕒
:o:kadomatsu::🎍
:o:cactus::🌵
:o:seedling::🌱
:o:berry::🍓〰️
:o:mushroom::🍄
:o:maple::🍁🌳
:o:nut::🥜
:o:clover::☘️
:o:fog::🌫️
:o:tornado::🌪️
:o:rainbow::🌈
:o:mount::⛰️
:o:fuji::🗻
:o:volcano::🌋
:o:happysun::🌞
:o:wave::🌊
:o:cutlery::🍴
:o:forkknife::🍴
:o:chopsticks::🥢
:o:icecream::🍦
:o:lollipop::🍭
:o:candy::🍭〰️
:o:pretzel::🥨
:o:clink::🥂
:o:toast::2?
:o:toast1::🥂🎬
:o:toast2::🍞
:o:honey::🍯
:o:cakepiece::🍰
:o:hamburger::🍔
:o:cherries::🍒
:o:peach::🍑
:o:wine::🍷
:o:cocktail::🍸
:o:tropicaldrink::🍹
:o:banana::🍌
:o:noodles::🍜
:o:pizza::🍕
:o:cart::🛒
:o:bike::🚲
:o:bicycle::🚲
:o:scooter::🛴
:o:vespa::🛵
:o:truck::🚚
:o:sled::🎿
:o:skier::⛷️
:o:satellite::🛰️
:o:helicopter::🚁
:o:rocket::🚀
:o:iceskates::⛸️
:o:ambulance::🚑
:o:moderntrain::🚆
:o:locomotive::🚂
:o:shinkansen::🚅
:o:metro::🚇
:o:houses::🏘️
:o:housegarden::🏡
:o:mosque::🕌
:o:church::⛪
:o:temple::🏛️
:o:mandir::🛕
:o:synagogue::🕍
:o:factory::🏭
:o:hospital::🏥
:o:tent::🎪〰️
:o:torii::⛩️
:o:castle::🏰
:o:trainstation::🚉
:o:tower::🗼
:o:axe::🪓
:o:pin::📌
:o:triangleruler::📐
:o:wrench::🔧
:o:razor::🪒
:o:safetypin::🧷
:o:broom::🧹
:o:gear::⚙️
:o:toolbox::🧰
:o:yarn::🧶
:o:tube::🧪
:o:research::🔬⭐
:o:microscope::🔬
:o:doctor::🩺🧒
:o:stethoscope::🩺
:o:extinguisher::🧯
:o:briefcase::💼
:o:drum::🥁
:o:violin::🎻
:o:mike::🎤‍
:o:film::2?
:o:film1::🎥🎬
:o:film2::🎥⭐
:o:filmcamera::🎥
:o:camera::📷
:o:syringe::💉
:o:sponge::🧽
:o:beads::📿
:o:bow::2?
:o:bow1::🏹
:o:bow2::🙇👌🎬
:o:tobow::🙇👌🎬
:o:trident::🔱
:o:swords::⚔️👌
:o:tobattle::⚔️🎬
:o:battle::⚔️🎬
:o:war::⚔️⭐
:o:shield::🛡️
:o:dagger::🗡️
:o:crystalball::🔮
:o:fortune::🔮⭐
:o:topredict::🔮🎬
:o:prediction::🔮🎬
:o:chemistry::⚗️⭐
:o:kite::🪁
:o:link::🔗
:o:connection::🔗⭐
:o:kimono::👘
:o:glasses::👓
:o:sunglasses::☀️👓
:o:boot::👢
:o:sneaker::👟
:o:ballet::🩰⭐
:o:balletshoes::🩰
:o:academichat::🎓
:o:academic::🎓🤲
:o:shirt::👕
:o:gloves::🧤
:o:scarf::🧣
:o:tophat::🎩
:o:ribbonhat::👒
:o:masks::🎭
:o:dress::👗
:o:pants::👖
:o:trousers::👖
:o:monocle::🧐👓
:o:expertise::🧐⭐
:o:expert::♾️⚖️💡🎬🧒
:o:bikini::👙
:o:briefs::🩲
:o:shorts::🩳
:o:swimsuit::🩱
:o:lipstick::💄
:o:ring::💍
:o:backpack::🎒
:o:receiver::📞
:o:closed::🔐🤲
:o:oldkey::🗝️
:o:tincan::🥫
:o:amphora::🏺
:o:alarmclock::⏰️
:o:alarm::2?
:o:alarm1::⏰️🔊
:o:alarm2::⚔️〰️📬📣🎬
:o:wetumbrella::☔
:o:umbrella::☂️
:o:laptop::💻
:o:balloon::🎈
:o:toilet::2?
:o:toilet1::🚽
:o:toilet2::🧻⚓
:o:toiletpaper::🧻
:o:dice::🎲🎲
:o:date::📆
:o:plaster::🩹
:o:getletter::📩
:o:magnet::🧲
:o:closedmailbox::📫
:o:cd::💿
:o:dvd::📀
:o:teddy::🧸
:o:calendar::📅
:o:battery::🔋
:o:controller::🎮
:o:headphones::🎧
:o:earphones::👂⏺️🎧
:o:computermouse::🖱️
:o:desktopmouse::🖱️
:o:monitor::🖥️
:o:flashlight::🔦
:o:keyboard::2?
:o:keyboard1::⌨️
:o:keyboard2::🎹👌
:o:puzzle::🧩⭐
:o:puzzlepiece::🧩
:o:diamond::💎
:o:goal::🏁
:o:whiteflag::🏳️
:o:blackflag::🏴
:o:crown::👑
:o:tag::🏷️
:o:scroll::📜
:o:ball::⚽〰️
:o:speaker::📢
:o:megaphone::📣
:o:barrier::🚧
:o:bowling::🎱⭐
:o:bowlingball::🎱
:o:clipboard::📋
:o:reception::🛎️⚓
:o:receptionbell::🛎️
:o:trophy::🏆
:o:bomb::💣
:o:dynamite::🧨
:o:pawn::♟
:o:books::📚
:o:snowman::⛄️
:o:partycone::🎉
:o:medal::🎖️
:o:cigarette::🚬
:o:cigar::🐘🤲🚬
:o:coffin::⚰️
:o:judo::🥋⭐
:o:moai::🗿
:o:nfl::🏈
:o:dart::🎯
:o:garbage::🗑️⭐
:o:antenna::📡👌
:o:hearts::💕
:o:cupid::💘
:o:angryshout::🗯️
:o:score::3?
:o:score1::🎼
:o:score2::❓💯
:o:score3::💯➕🎬
:o:above::⬆️⚓
:o:yes::✔️
:o:forbidden::👎
:o:loop::➰
:o:chart::📊
:o:dollar::💲
:o:bang::💥
:o:islam::☪️
:o:christianity::✝️
:o:hinduism::🕉️
:o:buddhism::☸️
:o:judaism::🕎
:o:davidstar::✡️
:o:points::💯⭐
:o:fullpoints::💯👌
:o:triangle::🔺
:o:speechless::😶🤲
:o:skull::💀👌
:o:skullbones::☠️👌
:o:brain::🧠
:o:gene::🧬
:o:dna::🧬
:o:bust::👤
:o:kneel::🧎
:o:shit::💩
:o:deny::🙅🎬
:o:no::🙅
:o:raisehand::🙋
:o:bride::👰🏻
:o:princess::👸
:o:wizard::🧙🏻
:o:mage::🧙🏻
:o:wizardess::🧙‍♀️
:o:witch::🧙‍♀️
:o:towrite::✍️🎬
:o:ghost::👻
:o:santa::🎅
:o:clown::🤡
:o:vampire::🧛
:o:mermaid::🧜
:o:surfer::🏄
:o:golfer::🏌️
:o:fencer::🤺
:o:disco::🕺⚓
:o:dancer::💃
:o:biker::🚴
:o:dot::▪️
:o:lightbulb::💡👌
:o:drizzle::💧👌🎬
:o:huge::🐘🐘🤲
:o:stray::⛔👥➕
:o:kitten::🤏🐈
:o:toperch::🪑➖🪑🎬
:o:perch::📏〰️
:o:rod::📏〰️
:o:pole::📏〰️
:o:firm::2?
:o:firm1::✊️👌🤲
:o:firm2::🔗👥
:o:shaky::👋🤲
:o:tohitch::🔗🎬
:o:hitch::🔗
:o:totile::🧩〰️🎬
:o:tile::🧩〰️
:o:tostretch::2?
:o:tostretch1::🧵🤲🔥🎬
:o:tostretch2::🧵🤲📦🎬
:o:mile::mi
:o:bill::2?
:o:bill1::🔢🤲📝
:o:bill2::💰🔢🤲📝
:o:tobeam::🌟🎬
:o:beam::📏〰️
:o:tomesh::🕸️〰️🔗🎬
:o:mesh::🕸️〰️🔗
:o:tomire::💩🤲🔥🎬
:o:mire::💩🤲❗
:o:oat::🌾
:o:topreserve::🧵🤲🕒👍🔥📦
:o:gay::4?
:o:gay1::🎨⭐🤲
:o:gay2::😃
:o:gay3::♂️♂️❤️🤲
:o:gay4::♀️♀️❤️🤲
:o:lesbian::2?
:o:lesbian1::♀️♀️❤️🤲
:o:lesbian2::♀️♀️❤️🧒
:o:port::🚢⚓
:o:harbour::🚢⚓
:o:peg::📏〰️
:o:court::🏰🔲⚓
:o:crate::📦👌
:o:shorten::🧵⚡️🤲🔥📦
:o:coal::🚂⛽💧⭐
:o:fuel::⛽💧⭐
:o:gasoline::⛽💧
:o:toshed::⛔👜✨🎬
:o:shed::🤏🏠
:o:hut::🤏🏠
:o:wilt::🥀🎬
:o:topile::📚〰️🎬
:o:pile::📚〰️
:o:torotate::🔄🎬
:o:tospin::🔄🎬
:o:brass::📯🧱⭐
:o:eyelid::👁️👒⭐
:o:droop::💪⚡️🤲
:o:tohang::2?
:o:tohang1::🧵💀🔥🎬
:o:tohang2::🌳🦥🎬
:o:gallows::🧵💀⚓
:o:tin::Sn
:o:absent::⛔👇⚓📦
:o:shaggy::🐏🌯⭐🤲
:o:broadleaf::🍃🌳
:o:bribe::🙅🤲💰✋️🎁🎬
:o:honest::✔️🤲
:o:mat::🛏⬇️🐋🤲📝
:o:totuck::🥢🎬
:o:topince::🥢🎬
:o:tocapture::🕸️🎬
:o:rug::👣⬇️⚓📝
:o:carpet::👣⬇️⚓📝
:o:dusty::💨👌🤲
:o:tocrack::💥🎬
:o:crack::💥🎬⚓
:o:chestnut::🌰
:o:walnut::🐋🤲🌰
:o:zest::🔥🧒💭
:o:enthusiasm::🔥🧒💭
:o:content::⏺️⚓❗
:o:todip::↘️👋🎬
:o:tosway::👋🎬
:o:brand::🔗👥❓📣
:o:nasty::💩🙅🤲
:o:topost::✉️🎬
:o:post::✉️🎬
:o:toowe::⚠️✋️🎁🎬
:o:cent::ct
:o:hinge::👋🎬🔗
:o:toquench::💧🎬
:o:cracker::🍪
:o:tune::🎵
:o:melody::🎵
:o:restless::🦥⛔💪🎬
:o:spice::👅⭐🧂⭐
:o:sheath::⚔️👌🌯⭐
:o:gaunt::📝🤏🧍🤲
:o:toslice::🔪🎬
:o:slice::🔪🎬📝⭐
:o:layer::📝⭐
:o:whiskey::🥃🍶〰️
:o:booze::🍶〰️
:o:charm::✨⭐
:o:pound::lb
:o:tobend::🦵🔗🎬
:o:totwist::🔄🎬
:o:twin::=🕒👶👶
:o:necklace::📿〰️
:o:earring::👂💍
:o:petal::🌼🍃
:o:puff::💨
:o:bare::🐚🤲
:o:stiff::✊️👌🤲
:o:rigid::✊️👌🤲
:o:bid::👋⭐
:o:bunch::👥
:o:smoky::🔥👌💨🤲
:o:distinct::🔀
:o:crowd::👥
:o:bucket::🛢️🤲❗
:o:stench::💩🤲💨
:o:odor::💩🤲💨
:o:steady::⛔👋🤲
:o:tocarve::🎃🔪🎬
:o:marble::〰️👌🥌⭐
:o:naked::⛔👚⭐🤲
:o:regisseur::🎥🤴🏻🎬🧒
:o:note::2?
:o:note1::🤏📝
:o:note2::🎵👌
:o:todespair::😱💭🎬
:o:porch::⏺️⚓⚡️🏠📦⭐
:o:tobeat::🥁🎬
:o:beat::🥁⭐
:o:totrack::👀✍️🎬
:o:track::2?
:o:track1::🚶⚓
:o:track2::🚗⚓
:o:speedy::🏃💨🤲
:o:pipe::🐚🤲📏〰️
:o:tender::🧈🤲
:o:tothrive::👍🎬
:o:toclaim::
:o:claim::2?
:o:claim1::⚖️⭐📖🔨💖
:o:claim2::✔️🤲📦🔍💬🎬
:o:fence::🚧〰️
:o:toplunge::↘️🎬
:o:hardware::⚙️⭐
:o:software::💻〰📝
:o:node::🎀〰️
:o:tostalk::🤫🚶🚶🎬
:o:stalk::🌼📏
:o:distance::🧵🤲⭐
:o:fierce::🦁🤲
:o:tojell::🧱🤲✨🎬
:o:toadmit::🙇❗🔍💬🎬
:o:toapologize::🙇🎬
:o:apology::🙇🎬
:o:cushion::🛏️👛〰️
:o:towhistle::👄🎵🎬
:o:lawn::🏠🌿⚓
:o:stuff::❗
:o:tohiss::💨🎵🎬
:o:valve::🌊✖️🎬⚙️⭐
:o:dam::🌊🛑🎬⚓
:o:tobathe::🛀🎬
:o:breeze::🤏💨
:o:rack::📏〰️🔲
:o:toripen::🍇🎬
:o:ripe::🍇📬🎬
:o:endure::👍⭐👣📦
:o:maintain::👍⭐👣🔥📦
:o:maintenance::🛠️⭐
:o:toplan::🏁🚶⭐🎬
:o:hazy::🌫️🤲
:o:vat::🛢️
:o:log::2?
:o:log1::🌳📏
:o:log2::✍️📝
:o:tolog::✍️🎬
:o:totumble::👋↘🎬
:o:towaver::👋🎬
:o:spot::⚓
:o:inheritance::👪☠️⛲📨🎬❗
:o:toinherit::👪☠️⛲📨🎬
:o:heir::☠️➡️🤲🧒
:o:successor::☠️➡️🤲🧒
:o:tosucceed::2?
:o:tosucceed1::🏁📬🚶🎬
:o:tosucceed2::🚶🚶🎬
:o:role::⚠️🎬❗
:o:tocrunch::🥌〰️🎬
:o:millstone::🌾⛲🧂⭐🥌〰️
:o:cop::👮‍
:o:bush::🐘🤲🌿
:o:bundle::💐〰️
:o:todrench::💧🎬
:o:damp::💧🤲
:o:bouquet::💐
:o:todrip::💧👌🎬
:o:dime::10ct⚪👌
:o:goose::🐘🤲🦆
:o:topad::⏺️📬⬇️✋️🎬
:o:pad::⏺️⚓❗
:o:topet::🐈✋️🎬
:o:pet::🏠🐒〰️
:o:filling::⏺️⚓❗
:o:pleasant::👍👥🤲
:o:gentle::🧈✋️🤲
:o:rum::🏝️🍶〰️
:o:tocreak::🌳🧱⭐🎵🎬
:o:frost::❄️
:o:troop::⚔️👥
:o:soldier::⚔️👥💦🧒
:o:twine::🧵
:o:tosever::🔪🎬
:o:phase::🕒💦
:o:totinge::🎨⭐🎬
:o:pullover::🧵🤲👚⭐
:o:sweater::🧵🤲👚⭐
:o:sleave::👚⭐🧍💪
:o:latch::2?
:o:latch1::🔐📏〰️🎬
:o:latch2::🔐📏〰️
:o:brew::♨️🤲💧🎬
:o:mob::🦁🤲👥
:o:rusty::❤️🎨⚓👌🤲
:o:tailor::2?
:o:tailor1::👚⭐🧱🎬
:o:tailor2::👚⭐🧱🧒
:o:toad::🐸🤲❗
:o:crawl::👣⬇️⚓🚶🎬
:o:ledge::⛰️🚧〰⬆️💦
:o:rear::🚶⬅️⚓
:o:passage::🚶⚓
:o:sleek::🧈🤲
:o:tocruise::🚢🎬
:o:todrift::🌊➕🚶🎬
:o:fin::🐟✋️
:o:tohatch::🥚🎬
:o:hatch::🤏🚪
:o:constant::⛔🔀🎬🤲
:o:variable::🔀🎬🤲
:o:item::❗
:o:tight::✊️👌🤲
:o:ray::☀️🔱
:o:underwear::⬇️⚓👚⭐
:o:submarine::🌊⬇️⚓🚢
:o:crow::🌙🕒🎨🐦
:o:raven::🌙🕒🎨🐦
:o:pattern::🧩〰️🔨⭐
:o:ankle::🦶🔗
:o:speech::💬
:o:suicide::↩️🧍☠️🔥🎬
:o:tomurder::🧒🔍☠️🔥🎬
:o:murder::🧒🔍☠️🔥🎬
:o:murderer::🧒🔍☠️🔥🎬🧒
:o:thankful::🙏🙏🤲
:o:rhythm::🥁⭐
:o:stables::🐴🏠
:o:tale::💬💬
:o:toclick::🖱️🎬
:o:cursor::🖱️➡️👌
:o:trump::♾️⚖️👍🃏
:o:totrump::♾️⚖️👍🃏🎬
:o:paperclip::📎
:o:circus::🤡⚓
:o:sample::〰️
:o:togrin::😃🎬
:o:in::2?
:o:in1::⚓
:o:in2::⏺️⚓
:o:on::⬆️⚓
:o:at::2?
:o:at1::⚓
:o:at2::🕒
:o:as::3?
:o:as1::📦
:o:as2::🤲
:o:as3::💡
:o:as4::⚖️
:o:them::2?
:o:them1::👆🧒
:o:them2::👆👥
:o:through::🔨
:o:togenerate::🧱🎬
:o:income::📨🎬💰
:o:imaginary::💭👀🤲
:o:expand::2?
:o:expand1::🐘🤲🔥📦
:o:expand2::❗❗🔥📦
:o:prefix::⬅️⚓🤏💬💦
:o:infix::⏺️⚓🤏💬💦
:o:suffix::➡️⚓🤏💬💦
:o:magnificent::🌟👍
:o:sack::👛〰️
:o:purse::👛
:o:homepage::💻⭐🕸️📝
:o:website::💻⭐🕸️📝
:o:network::🕸️⭐
:o:ham::🍖📝
:o:sandwich::🥪
:o:rare::♾️⚪⛔🤲
:o:unusual::♾️⚪⛔🤲
:o:seldom::🌴🌴🕒
:o:rarely::🌴🌴🕒
:o:pleasure::😃
:o:verse::📏⭐💬💦
:o:rhyme::🔊☝️🤲💬💦
:o:synonym::=💭🔥🎬💬💦
:o:unclear::👍💧👀⛔🤲
:o:beast::👹〰️
:o:tissue::2?
:o:tissue1::🤧📝
:o:tissue2::🧱⭐
:o:unpopular::🧒🧒☝️⛔❤️🎬
:o:despise::💢🎬
:o:shopping::🛍️🎬
:o:movement::2?
:o:movement1::🧍👋🎬
:o:movement2::🔥💖🎬👥
:o:swine::🐷
:o:piglet::🤏🐷
:o:drunk::🤯🍶〰️🤲
:o:tohandle::🎬
:o:handle::👜👌⬆️💦
:o:todeal::2?
:o:todeal1::🎬
:o:todeal2::✋️🎁🎬
:o:deal::🤝⭐
:o:tosolve::2?
:o:tosolve1::➰🤲🔥📦
:o:tosolve2::👍⭐🔥📦
:o:browser::💻⭐🕸️🖥️
:o:cliff::⛰️🚧〰️
:o:canyon::⛰⬇️💦🚶⚓
:o:radioactive::☢️
:o:biohazard::☣️
:o:chess::♟⭐
:o:tocheck::👀🎬
:o:check::♟⭐🤴🏻🔍⚔️🎬
:o:checkmate::🤴🏻☠️
:o:oven::🎂🧱🎬⚓
:o:pasta::🍝
:o:spaghetti::🍝
:o:lovely::❤️🤲
:o:curry::2?
:o:curry1::🍛
:o:curry2::🍛🧂⭐
:o:bento::🍱
:o:cookedrice::🍚
:o:stew::🍲
:o:sweetpotato::🍠
:o:worst::♾️⚖️👎
:o:oden::🍢
:o:fries::🍟
:o:shavedice::🍧
:o:izakaya::🏮⭐
:o:servant::🐶🎬🧒
:o:civil::2?
:o:civil1::♾️🧒🎁
:o:civil2::🧒〰️🌍⭐🤲
:o:garlic::🧄
:o:cinnamon::☕🎨🌼📏🧂⭐
:o:foe::👎👥🧒
:o:panther::🌙🕒🎨🐆
:o:excuse::🙇
:o:topardon::🙇➡️👍⭐🎬
:o:lover::❤️🧒
:o:does::🎬
:o:blade::🔪🍃
:o:stubborn::🧱👌🧒👌🤲
:o:pedantic::🤏⭐👀🎬
:o:snowstorm::🌨️❄️💨
:o:blizzard::🌨️❄️💨
:o:toexplode::💣💥🎬
:o:explosion::💣💥
:o:fireworks::🧨⭐
:o:firecracker::🧨
:o:whose::❓🧒
:o:petridish::🧫
:o:cylinder::🎩👤⭐
:o:haircut::🧒👌🌿🔨⭐
:o:sunflower::🌼👌
:o:patent::☎️〰️©️
:o:banner::🏳️
:o:saga::💬💬
:o:martialarts::🥋⭐
:o:belt::👖➰
:o:band::2?
:o:band1::👥
:o:band2::🎵👥
:o:musician::🎵🧒
:o:artist::🎨〰️🧒
:o:todesign::👤⭐🎬
:o:design::👤⭐🎬
:o:designer::👤⭐🎬🧒
:o:handy::🔨💪🎬
:o:toyell::📣🎬
:o:yuck::💩🤲
:o:obnoxious::💩🤲
:o:file::📁📝
:o:folder::📁
:o:filecabinet::🗄️
:o:cardbox::🗃️
:o:token::🤏❗
:o:solace::😢🛑🎬
:o:pussy::2?
:o:pussy1::🐈
:o:pussy2::👩🕳
:o:anal::🧍🍑⭐🕳🤲
:o:toinsert::⏺️📬⬇️✋️🎬
:o:toload::2?
:o:toload1::⏺️📬⬇️✋️🎬
:o:toload2::⬇️💾🎬
:o:toclamp::🗜️🎬
:o:clamp::🗜️
:o:tomine::⚒️🎬
:o:mine::⚒️⚓
:o:communism::⚒️⭐🤴🏻👥
:o:capitalism::💰🤴🏻🎬
:o:socialism::♾️👥🎁🤴🏻👥⭐
:o:revolution::👥⭐🔀🔥🎬
:o:webdesign::💻⭐🕸️👤⭐🎬
:o:webdesigner::💻⭐🕸️👤⭐🎬🧒
:o:engineer::⚙️⭐🧒
:o:tutorial::💡🔥🎬📝
:o:textbook::💡🔥🎬📖
:o:oral::👄🤲
:o:earplug::👂📏〰️
:o:quantum::🤏🔢
:o:cannon::🐘🤲🔫⭐
:o:todrain::🚶💨🌊🎬
:o:drain::🚶💨🌊🎬⚓
:o:basin::💧🛁〰️
:o:license::⚖️⭐📖🔨⭐
:o:hood::👛〰️🧢
:o:destination::🏁
:o:variety::🔀🔀
:o:toadapt::👀〰️➕🔀🎬
:o:circumstance::❓🤲⭐
:o:toadopt::2?
:o:toadopt1::🔀🧬👪🧒📨🎬
:o:toadopt2::🔨⛲🎬
:o:foster::🔀🧬
:o:toemploy::🔨🎬
:o:employee::🔨🎬🤲🧒
:o:tojuggle::🤹🎬
:o:cannot::⛔💪
:o:dubious::🙅🤲🔍💭🎬🤲
:o:booklet::🤏📖
:o:concept::💭💦
:o:depth::🕳🤲⭐
:o:contract::⚖️⭐📖🤝⭐
:o:legalese::⚖️⭐📖💬🔨⭐
:o:chin::👄⬇️⚓
:o:beard::🧔👌🌿
:o:cheek::👄⬅️➡️⚓
:o:target::🏁
:o:rumor::🤫💬
:o:pill::💊
:o:alphabet::🔤👥
:o:toinsinuate::💭🔥🎬
:o:insinuation::💭🔥🎬
:o:dear::❤️🤲
:o:indeed::✔️🤲
:o:once::2?
:o:once1::1🕒
:o:once2::⬅️🕒
:o:perhaps::🤔
:o:bubble::🧼⚪👌
:o:convenient::🙂🎬🤲
:o:convenience::🙂🎬❗
:o:inconvenient::😧🎬🤲
:o:inconvenience::😧🎬❗
:o:baker::🍞〰️🧒
:o:carpenter::🌳⛲🧱🎬🧒
:o:butler::🐶🎬🧒
:o:carter::🚗🧒
:o:harp::🧵✋🎵🔨〰️
:o:harper::🧵✋🎵🔨〰️🧒
:o:string::🧵
:o:potter::🏺🧱🎬🧒
:o:webster::👚⭐🔗🎬🧒
:o:confused::😕
:o:toconfuse::2?
:o:toconfuse1::⛔💡🔥🎬
:o:toconfuse2::⛔💡🎬
:o:nonbinary::➖♂️➖♀️
:o:toenslave::⛓️🎬
:o:slavery::🧒⛓️⭐
:o:topolect::⚓💬🔨⭐
:o:dialect::👥💬🔨⭐
:o:blouse::👚
:o:cowardice::🦁⚡️🤲⭐
:o:correctness::✔️🤲⭐
:o:sometime::❗🕒
:o:treason::🚶🔍🗡️🎬
:o:betrayal::🚶🔍🗡️🎬
:o:tobetray::🚶🔍🗡️🎬
:o:resign::😫💡⛔👣🎬
:o:standard::♾️🎁=❗
:o:default::♾️🎁=❗
:o:tobeg::🙏🎬
:o:toimplore::🙏🎬
:o:toallow::👍🔥🎬
:o:toprohibit::👎🔥🎬
:o:todisallow::👎🔥🎬
:o:tosuggest::🎁💬🎬
:o:beach::🏖️
:o:toruin::💥📬🎬
:o:ruin::💥📬🎬🤲❗
:o:tostun::😲🔥🎬
:o:salmon::〰️👌🐟
:o:barn::🤏🏠
:o:severe::🏋️🤲
:o:tolean::🤏↘️🎬
:o:lean::📝👌🤲
:o:plush::🦆🤲
:o:dictionary::💬💦📖
:o:unfriendly::👎👥🤲
:o:todamage::🤕🔥🎬
:o:android::🧒〰⚙️⭐
:o:tocurve::↪️🎬
:o:curve::↪️👌
:o:leftcurve::↪️
:o:rightcurve::↩️
:o:liberty::⛓️⚡️
:o:happiness::😃
:o:toexit::🚶💨🎬
:o:exit::🚶💨🎬🚪
:o:abit::🤏🤲
:o:toblow::💥🏁🎬
:o:totoboard::🚉🎬
:o:call::📣
:o:run::🏃
:o:toinvite::👋⭐🎬
:o:tohelp::🎁🎬
:o:totry::👀⭐🎬
:o:tostart::⛲🎬
:o:tocontinue::👣🎬
:o:tobecome::✨📦
:o:tostop::2?
:o:tostop1::🛑🔥🎬
:o:tostop2::🛑🎬
:o:toadd::➕🎬
:o:tosubtract::➖🎬
:o:toexclude::➖🎬
:o:toinclude::➕🎬
:o:tohate::💢🎬
:o:towant::💖🎬
:o:tonotwant::💔🎬
:o:shy::🦌💨🤲
:o:timid::🦌💨🤲
:o:northpole::♾️⚖️🧭⬆️⚓
:o:southpole::♾️⚖️🧭⬇️⚓
:o:america::🌎⚪⚓
:o:northamerica::🌎💦⬆️
:o:southamerica::🌎💦⬇️
:o:europe::EU🌍⚓
:o:africa::🦏🌍⚓
:o:eastasia::🌏💦⬆️
:o:asia::🌍🌏💦⬆️
:o:australia::🦘🌏⚓
:o:indoasia::🌏💦⬇️
:o:arctic::🌍⬆️🧊⚓
:o:antarctic::🌍⬇️🧊⚓
:o:pacific::🌏🌎🌊⚓
:o:atlantic::🌎🌍🌊⚓
:o:indianocean::🌍🌏🌊⚓
:o:region::⚪⚓
:o:scandinavia::🧭⬆️EU🌍⚓
:o:northsea::EU🌍⚓🧭⬆️🌊⚓
:o:mediterranean::EU🌍⚓🧭⬇️🌊⚓
:o:panda::🐼
:o:china::CN🌏🏳️
:o:india::IN🌏🏳️
:o:usa::US🌎🏳️
:o:indonesia::ID🌏🏳️
:o:pakistan::PK🌏🏳️
:o:nigeria::NG🌍🏳️
:o:brazil::BR🌎🏳️
:o:bangladesh::BD🌏🏳️
:o:russia::RU🌏🏳️
:o:mexico::MX🌎🏳️
:o:japan::JP🌏🏳️
:o:philippines::PH🌏🏳️
:o:ethiopia::ET🌍🏳️
:o:egypt::EG🌍🏳️
:o:vietnam::VN🌏🏳️
:o:congo::CD🌍🏳️
:o:iran::IR🌍🏳️
:o:turkey::TR🌍🏳️
:o:germany::DE🌍🏳️
:o:france::FR🌍🏳️
:o:unitedkingdom::UK🌍🏳️
:o:uk::UK🌍🏳️
:o:thailand::TH🌏🏳️
:o:tanzania::TZ🌍🏳️
:o:southafrica::ZA🌍🏳️
:o:italy::IT🌍🏳️
:o:myanmar::MM🌏🏳️
:o:southkorea::KR🌏🏳️
:o:korea::KP+KR🌏🏳️
:o:colombia::CO🌎🏳️
:o:spain::ES🌍🏳️
:o:kenya::KE🌍🏳️